packages:
  - "examples/*/*"
  - ".github/publish-ci/*"
  - "integration/fixtures/**/vendor/*"
  - "."

overrides:
  "js-yaml@>=4.0.0 <4.3.1": "4.3.1"
  "postcss@<8.5.23": "8.5.25"
  "undici@>=7.0.0 <7.29.0": "7.29.0"
  "uuid@<11.1.1": "11.1.1"
