import {
  getNormalizeModuleFederationOptions,
  getNormalizeShareItem,
  isExplicitSharedKey,
  NormalizedModuleFederationOptions,
  ShareItem,
} from '../utils/normalizeModuleFederationOptions';
import {
  getInstalledPackageJson,
  getPackageName,
  getSharedCacheDescriptor,
  hasPackageDependency,
  packageNameEncode,
  sharedCacheHelperCode,
} from '../utils/packageUtils';
import { serializeRuntimeOptions } from '../utils/serializeRuntimeOptions';
import VirtualModule from '../utils/VirtualModule';
import { getVirtualExposesId } from './virtualExposes';
import { getUsedRemotesMap } from './virtualRemotes';
import {
  getRuntimeInitBootstrapCode,
  getRuntimeInitResolveBootstrapCode,
  getRuntimeInitStatusImportId,
  getRuntimeModuleCacheBootstrapCode,
} from './virtualRuntimeInitStatus';
import {
  getConcreteSharedImportSource,
  getLocalProviderImportPath,
  getProjectResolvedImportPath,
  getSharedImportSource,
  getSharedNamedExports,
  getTreeShakingSharedProviderImportId,
  hasTreeShakingSharedProvider,
} from './virtualShared_preBuild';
import { getTreeShakingExportUsage } from '../utils/treeShaking';

let usedShares: Set<string> = new Set();
const usedSharesByOptions = new WeakMap<NormalizedModuleFederationOptions, Set<string>>();

function getScopedUsedShares(options: NormalizedModuleFederationOptions) {
  let scoped = usedSharesByOptions.get(options);
  if (!scoped) {
    scoped = new Set();
    usedSharesByOptions.set(options, scoped);
  }
  return scoped;
}

export function getUsedShares(options?: NormalizedModuleFederationOptions) {
  if (options) return getScopedUsedShares(options);
  return usedShares;
}
export function addUsedShares(pkg: string, options?: NormalizedModuleFederationOptions) {
  usedShares.add(pkg);
  if (options) getScopedUsedShares(options).add(pkg);
}
const LOCAL_SHARED_IMPORT_MAP_ID = 'virtual:mf-localSharedImportMap';

const localOwnerIds = new WeakMap<NormalizedModuleFederationOptions, number>();
let nextLocalOwnerId = 1;

function getLocalOwnerKey(options: NormalizedModuleFederationOptions) {
  let ownerId = localOwnerIds.get(options);
  if (!ownerId) {
    ownerId = nextLocalOwnerId++;
    localOwnerIds.set(options, ownerId);
  }
  return `${options.internalName}__mf_owner__${ownerId}`;
}

export function getLocalSharedImportMapPath(options?: NormalizedModuleFederationOptions) {
  const resolvedOptions = options ?? getNormalizeModuleFederationOptions();
  const ownerName = options
    ? getLocalOwnerKey(resolvedOptions)
    : resolvedOptions.internalName || resolvedOptions.name;
  return `${LOCAL_SHARED_IMPORT_MAP_ID}:${packageNameEncode(ownerName)}`;
}

export function getResolvedLocalSharedImportMapId(options?: NormalizedModuleFederationOptions) {
  return `\0${getLocalSharedImportMapPath(options)}`;
}

let invalidateLocalSharedImportMap: (() => void) | undefined;
const localSharedImportMapInvalidators = new WeakMap<
  NormalizedModuleFederationOptions,
  () => void
>();
export function setLocalSharedImportMapInvalidator(
  invalidator: (() => void) | undefined,
  options?: NormalizedModuleFederationOptions
) {
  if (!options) {
    invalidateLocalSharedImportMap = invalidator;
  } else if (invalidator) {
    localSharedImportMapInvalidators.set(options, invalidator);
  } else {
    localSharedImportMapInvalidators.delete(options);
  }
}

export function writeLocalSharedImportMap(options?: NormalizedModuleFederationOptions) {
  // The map is generated by the loader. Avoid rebuilding a large string every
  // time another shared module is discovered during resolution.
  (options ? localSharedImportMapInvalidators.get(options) : invalidateLocalSharedImportMap)?.();
}

function shouldUseDirectReactImport() {
  const isVinext = hasPackageDependency('vinext');
  const isAstro = hasPackageDependency('astro');
  return isVinext || isAstro;
}

function getLocalSharedPackagePath(
  pkg: string,
  shareItem: ShareItem,
  options?: NormalizedModuleFederationOptions
) {
  const useDirectReactImport = shouldUseDirectReactImport();
  if (useDirectReactImport && pkg === 'react') return 'react';

  return (
    getConcreteSharedImportSource(pkg, shareItem) ||
    getLocalProviderImportPath(pkg) ||
    getSharedImportSource(pkg, shareItem, options)
  );
}

function getDirectSharedCacheSeedImportPath(pkg: string, shareItem: ShareItem) {
  return (
    getConcreteSharedImportSource(pkg, shareItem) ||
    getProjectResolvedImportPath(pkg) ||
    getLocalProviderImportPath(pkg) ||
    pkg
  );
}

export function generateLocalSharedImportMap(options?: NormalizedModuleFederationOptions) {
  const resolvedOptions = options ?? getNormalizeModuleFederationOptions();
  const useDirectReactImport = shouldUseDirectReactImport();
  const orderedShares = getOrderedUsedShares(options);
  const eagerImports = orderedShares
    .map((pkg, index) => {
      const shareItem = getNormalizeShareItem(pkg, resolvedOptions);
      if (!shareItem?.shareConfig.eager || shareItem.shareConfig.import === false) return '';
      return `import * as __mfEagerShare_${index} from ${JSON.stringify(
        getLocalSharedPackagePath(pkg, shareItem, options)
      )};`;
    })
    .filter(Boolean)
    .join('\n');

  return `
    import {loadShare} from "@module-federation/runtime";
    ${eagerImports}
    const importMap = {
      ${orderedShares
        .map((pkg, index) => {
          const shareItem = getNormalizeShareItem(pkg, resolvedOptions);
          return `
        ${JSON.stringify(pkg)}: async () => {
          ${
            shareItem?.shareConfig.import === false
              ? `throw new Error(\`[Module Federation] Shared module '\${${JSON.stringify(pkg)}}' must be provided by host\`);`
              : shareItem?.shareConfig.eager
                ? `let pkg = __mfEagerShare_${index};
            return pkg;`
                : `let pkg = await import(${JSON.stringify(getLocalSharedPackagePath(pkg, shareItem, options))});
            return pkg;`
          }
        }
      `;
        })
        .join(',')}
    }
      const usedShared = {
      ${getOrderedUsedShares(options)
        .map((key) => {
          const shareItem = getNormalizeShareItem(key, resolvedOptions);
          if (!shareItem) return null;
          const detectedNamedExports = getSharedNamedExports(key, shareItem);
          const canLiveRebind =
            shareItem.shareConfig.import === false || detectedNamedExports !== undefined;
          // A partial runtime provider cannot back an ESM proxy whose complete
          // export surface is unknown. Keep that share on its coherent local
          // namespace instead of selecting a different tree provider.
          const treeShakingConfig = canLiveRebind ? shareItem.shareConfig.treeShaking : undefined;
          const treeShakingUsage = treeShakingConfig
            ? getTreeShakingExportUsage(key, shareItem, shareItem.name, options)
            : undefined;
          const treeShakingProviderExports =
            treeShakingUsage?.kind === 'exports' ? treeShakingUsage.usedExports : [];
          const treeShakingUsedExports =
            resolvedOptions.injectTreeShakingUsedExports === false
              ? treeShakingConfig?.usedExports || []
              : treeShakingProviderExports;
          // Runtime inference is only sound when the consumer publishes the
          // exports discovered by this build. If injection is disabled, keep
          // the complete provider as the safe fallback instead of advertising
          // a partial provider with incomplete coverage metadata.
          const disableRuntimeInference =
            treeShakingConfig?.mode === 'runtime-infer' &&
            resolvedOptions.injectTreeShakingUsedExports === false;
          const treeShakingProviderImportId =
            treeShakingConfig &&
            !disableRuntimeInference &&
            hasTreeShakingSharedProvider(key, shareItem, options)
              ? getTreeShakingSharedProviderImportId(key, options)
              : undefined;
          const treeShakingStatus =
            treeShakingUsage?.kind === 'full' ||
            disableRuntimeInference ||
            (treeShakingConfig?.mode === 'runtime-infer' &&
              !treeShakingProviderImportId &&
              shareItem.shareConfig.import !== false)
              ? 0
              : 1;
          return `
          ${JSON.stringify(key)}: {
            name: ${JSON.stringify(key)},
            version: ${JSON.stringify(shareItem.version)},
            scope: [${JSON.stringify(shareItem.scope)}],
            loaded: false,
            eager: ${Boolean(shareItem.shareConfig.eager)},
            from: ${JSON.stringify(resolvedOptions.name)},
            canLiveRebind: ${canLiveRebind},
            async get () {
              if (${shareItem.shareConfig.import === false}) {
                throw new Error(\`[Module Federation] Shared module '\${${JSON.stringify(key)}}' must be provided by host\`);
              }
              usedShared[${JSON.stringify(key)}].loaded = true
              const {${JSON.stringify(key)}: pkgDynamicImport} = importMap
              const res = await pkgDynamicImport()
              const exportModule = ${JSON.stringify(useDirectReactImport)} && ${JSON.stringify(key)} === "react"
                ? (res?.default ?? res)
                : {...res}
              // All npm packages pre-built by vite will be converted to esm
              if (exportModule.__esModule !== true) {
                Object.defineProperty(exportModule, "__esModule", {
                  value: true,
                  enumerable: false
                })
              }
              return function () {
                return exportModule
              }
            },
            shareConfig: {
              singleton: ${shareItem.shareConfig.singleton},
              requiredVersion: ${JSON.stringify(shareItem.shareConfig.requiredVersion)},
              strictVersion: ${shareItem.shareConfig.strictVersion},
              eager: ${Boolean(shareItem.shareConfig.eager)},
              ${shareItem.shareConfig.import === false ? 'import: false,' : ''}
            },
            ${
              treeShakingConfig
                ? `treeShaking: {
              mode: ${JSON.stringify(treeShakingConfig.mode)},
              usedExports: ${JSON.stringify(treeShakingUsedExports)},
              providedExports: ${JSON.stringify(treeShakingProviderExports)},
              status: ${treeShakingStatus},
              ${
                treeShakingProviderImportId
                  ? `async get() {
                const container = await import(${JSON.stringify(treeShakingProviderImportId)});
                if (typeof container.init === "function") await container.init();
                return container.get();
              },`
                  : ''
              }
            }`
                : ''
            }
          }
        `;
        })
        .filter((x) => x !== null)
        .join(',')}
    }
      const usedRemotes = [${Object.keys(getUsedRemotesMap(options))
        .map((key) => {
          const remote = resolvedOptions.remotes[key];
          if (!remote) return null;
          return `
                {
                  alias: ${JSON.stringify(key)},
                  entryGlobalName: ${JSON.stringify(remote.entryGlobalName)},
                  name: ${JSON.stringify(remote.name)},
                  type: ${JSON.stringify(remote.type)},
                  entry: ${JSON.stringify(remote.entry)},
                  shareScope: ${JSON.stringify(remote.shareScope ?? 'default')},
                }
          `;
        })
        .filter((x) => x !== null)
        .join(',')}
      ]
      export {
        usedShared,
        usedRemotes
      }
      `;
}

function getOrderedUsedShares(options?: NormalizedModuleFederationOptions) {
  const resolvedOptions = options ?? getNormalizeModuleFederationOptions();
  const shares = new Set(getUsedShares(options));
  Object.keys(resolvedOptions.shared).forEach((pkg) => {
    if (!pkg.endsWith('/')) shares.add(pkg);
  });
  const sorted = Array.from(shares).sort((a, b) => {
    const priority = (pkg: string) =>
      pkg === 'react' ? 0 : pkg === 'react-dom' ? 1 : pkg.startsWith('react/') ? 2 : 3;
    return priority(a) - priority(b) || a.localeCompare(b);
  });
  return orderSharedDependenciesFirst(sorted);
}

function orderSharedDependenciesFirst(sharedPackages: string[]) {
  const sharedKeyByPackageName = new Map<string, string>();
  const subpathKeysByPackageName = new Map<string, string[]>();
  sharedPackages.forEach((pkg) => {
    const packageName = getPackageName(pkg);
    const existing = sharedKeyByPackageName.get(packageName);
    if (!existing || pkg === packageName) {
      sharedKeyByPackageName.set(packageName, pkg);
    }
    if (pkg !== packageName) {
      const subpaths = subpathKeysByPackageName.get(packageName);
      if (subpaths) subpaths.push(pkg);
      else subpathKeysByPackageName.set(packageName, [pkg]);
    }
  });
  const visiting = new Set<string>();
  const visited = new Set<string>();
  const ordered: string[] = [];
  const visit = (pkg: string) => {
    if (visited.has(pkg)) return;
    if (visiting.has(pkg)) return;
    visiting.add(pkg);
    const packageName = getPackageName(pkg);
    const packageJson =
      getInstalledPackageJson(pkg)?.packageJson ??
      (pkg !== packageName ? getInstalledPackageJson(packageName)?.packageJson : undefined);
    const dependencies = {
      ...((packageJson?.dependencies as Record<string, string> | undefined) || {}),
      ...((packageJson?.peerDependencies as Record<string, string> | undefined) || {}),
      ...((packageJson?.optionalDependencies as Record<string, string> | undefined) || {}),
    };
    Object.keys(dependencies).forEach((dependency) => {
      const sharedDependency = sharedKeyByPackageName.get(dependency);
      if (sharedDependency) visit(sharedDependency);
    });
    // Most packages can consume their own shared subpath exports through
    // self-referencing bare specifiers at module-evaluation time, so subpath
    // share keys must come before their package root (see #767, #805).
    // React's subpath implementations have the opposite dependency: React 18
    // evaluates react/jsx-runtime against ReactSharedInternals from the root
    // package. Initializing the subpath first crashes in dev (see #924).
    if (pkg === packageName) {
      const subpaths = subpathKeysByPackageName.get(packageName) || [];
      const rootMustBeInitializedFirst = packageName === 'react' || packageName === 'react-dom';
      if (rootMustBeInitializedFirst) {
        visiting.delete(pkg);
        visited.add(pkg);
        ordered.push(pkg);
        subpaths.forEach(visit);
        return;
      }
      subpaths.forEach(visit);
    }
    visiting.delete(pkg);
    visited.add(pkg);
    ordered.push(pkg);
  };
  sharedPackages.forEach(visit);
  return ordered;
}

function getShareItemForPreload(
  pkg: string,
  options: NormalizedModuleFederationOptions = getNormalizeModuleFederationOptions()
) {
  const shared = options.shared;
  const packageName = pkg.startsWith('@')
    ? pkg.split('/').slice(0, 2).join('/')
    : pkg.split('/')[0];
  const wildcardKey = `${packageName}/`;

  if (isExplicitSharedKey(pkg, options)) return shared[pkg];
  if (isExplicitSharedKey(wildcardKey, options)) return shared[wildcardKey];
  return undefined;
}

function generateSharedCacheSeedItem(
  pkg: string,
  shareItem: ShareItem,
  importPath: string,
  options: NormalizedModuleFederationOptions = getNormalizeModuleFederationOptions()
) {
  const cacheDescriptor = getSharedCacheDescriptor(pkg, shareItem);
  const cacheOwner = options.name;
  return `if (__mfReadSharedCache(__mfModuleCache.share, ${JSON.stringify(cacheDescriptor)}) === undefined) {
        const mod = await import(${JSON.stringify(importPath)});
        ${normalizeRuntimeShareCode}
        const normalizedModule = __mfNormalizeRuntimeShare(mod);
        const exportModule = normalizedModule === mod ? {...mod} : normalizedModule;
        if (exportModule.__esModule !== true) Object.defineProperty(exportModule, "__esModule", {
          value: true,
          enumerable: false
        });
        __mfWriteSharedCache(__mfModuleCache.share, ${JSON.stringify(cacheDescriptor)}, exportModule, ${JSON.stringify(cacheOwner)});
      }`;
}

const normalizeRuntimeShareCode = `const __mfNormalizeRuntimeShare = (mod) => {
            let current = mod;
            for (let i = 0; i < 5; i++) {
              const defaultExport = current?.default;
              if (!defaultExport || typeof defaultExport !== "object" || Object.keys(defaultExport).length === 0) break;
              const namedValues = Object.keys(current).filter((key) => key !== "default").map((key) => current[key]);
              if (namedValues.length > 0 && namedValues.some((value) => value !== undefined)) break;
              current = defaultExport;
            }
            return current;
          };`;

// Emitted into remoteEntry for shared provider selection.
export const sharedProviderSelectionHelperCode = `const __mfOriginalProviderKey = Symbol("mf.originalSharedProvider");
          const __mfResolveShareHook = { emit: (params) => params };
          const __mfCreateProviderSelectionVersions = (versions, strategy) => {
            if (strategy !== "version-first") return versions;
            const selectionVersions = {};
            for (const [version, provider] of Object.entries(versions)) {
              selectionVersions[version] = Object.assign({}, provider, {
                [__mfOriginalProviderKey]: provider
              });
            }
            return selectionVersions;
          };
          const __mfFindSharedProviderEntry = (versions, provider) => {
            if (!provider) return undefined;
            const entries = Object.entries(versions || {});
            const registeredEntry = entries.find(([, candidate]) => candidate === provider);
            if (registeredEntry) {
              return { version: registeredEntry[0], provider, registered: true };
            }
            if (typeof provider.version === "string" && provider.version) {
              return { version: provider.version, provider, registered: false };
            }
            const provenanceEntries = entries.filter(([, candidate]) =>
              candidate === provider || Boolean(provider.from && candidate?.from === provider.from)
            );
            if (provenanceEntries.length !== 1) return undefined;
            return { version: provenanceEntries[0][0], provider, registered: false };
          };
          const __mfSelectSharedProvider = (
            versions,
            pkg,
            share,
            strategy
          ) => {
            if (!versions || !share) return undefined;
            const scopes = Array.isArray(share.scope) ? share.scope : [share.scope || "default"];
            const selectionVersions = __mfCreateProviderSelectionVersions(versions, strategy);
            const shareScopeMap = {};
            for (const scope of scopes) {
              shareScopeMap[scope || "default"] = { [pkg]: selectionVersions };
            }
            const selected = runtimeShare.getRegisteredShare(
              shareScopeMap,
              pkg,
              { ...share, scope: scopes, strategy },
              __mfResolveShareHook
            )?.shared;
            return selected?.[__mfOriginalProviderKey] || selected;
          };`;

export const externalSharedProviderSelectionHelperCode = `const __mfSelectExternalSharedProvider = (
            versions,
            pkg,
            localShare,
            strategy
          ) => {
            const isLocalProvider = (provider) => __mfMatchesSharedProvider(provider, localShare);
            const candidates = Object.fromEntries(
              Object.entries(versions || {}).filter(([, provider]) => !isLocalProvider(provider))
            );
            if (localShare?.version) {
              const sameVersionProvider = candidates[localShare.version];
              // Runtime registration keeps an existing same-version record,
              // even when it has only a getter and is not loaded yet. Model
              // that retained provider here so pre-init seeding cannot choose
              // the local module while loadShare() later chooses the parent.
              if (!sameVersionProvider) {
                candidates[localShare.version] = localShare;
              }
            }
            const provider = __mfSelectSharedProvider(
              candidates,
              pkg,
              localShare,
              strategy
            );
            return isLocalProvider(provider) ? undefined : provider;
          };
          const __mfMatchesSharedProvider = (provider, expected) => provider === expected || Boolean(
            expected?.from && provider?.from === expected.from
          );
          const __mfGetScopeRootProvider = (
            instances,
            scopeRoot,
            shared,
            scopeName,
            pkg,
            version,
            provider,
            passedProvider,
            strategy
          ) => {
            if (strategy !== "version-first" || !passedProvider) return undefined;
            const scopeRootProviders = scopeRoot?.options?.shared?.[pkg];
            const configuredScopeRootProvider = Array.isArray(scopeRootProviders)
              ? scopeRootProviders.find((candidate) => candidate?.version === version)
              : undefined;
            const registeredScopeRootProvider = passedProvider?.from === scopeRoot?.options?.name
              ? passedProvider
              : undefined;
            const scopeRootProvider = registeredScopeRootProvider || (
              __mfMatchesSharedProvider(configuredScopeRootProvider, passedProvider)
                ? configuredScopeRootProvider
                // A plain Webpack/Rspack host has no enhanced-runtime instance.
                // Its pre-init snapshot is still authoritative when this remote's
                // registration rewrites the same-version provider in-place.
                : scopeRoot ? undefined : passedProvider
            );
            if (!scopeRootProvider) return undefined;
            const selectedFromLaterInstance = instances.some((instance) =>
              instance !== scopeRoot &&
              instance?.options?.name === provider?.from &&
              instance?.shareScopeMap?.[scopeName] === shared
            );
            return selectedFromLaterInstance ? scopeRootProvider : undefined;
          };
          const __mfResolveExternalSharedProvider = (
            instances,
            scopeRoot,
            shared,
            scopeName,
            pkg,
            providerEntry,
            selectedExternalProvider,
            passedProvider,
            strategy
          ) => {
            const scopeRootProvider = providerEntry.registered ? __mfGetScopeRootProvider(
              instances,
              scopeRoot,
              shared,
              scopeName,
              pkg,
              providerEntry.version,
              providerEntry.provider,
              passedProvider,
              strategy
            ) : undefined;
            const provider = scopeRootProvider || selectedExternalProvider;
            if (!provider) return undefined;
            if (
              providerEntry.registered &&
              !__mfMatchesSharedProvider(provider, passedProvider)
            ) return undefined;
            return { provider, scopeRootProvider };
          };`;

function generateRuntimeSharedCacheSeedCode(shareStrategy: string) {
  // Seeding a share evaluates its module graph, and every share proxy hit
  // during that evaluation must already be cached — the proxies defer their
  // local fallback until after init, so an unseeded proxy leaves its named
  // exports undefined at module-evaluation time. Seed dependencies and a
  // package's own subpath shares before the package itself.
  const seedOrder = getOrderedUsedShares();
  return `
    const __mfSeedOrder = ${JSON.stringify(seedOrder)};
    const __mfSeedKeys = __mfSeedOrder.filter((pkg) => usedShared[pkg] !== undefined);
    const __mfSeedPackageName = (pkg) => pkg.startsWith('@')
      ? pkg.split('/').slice(0, 2).join('/')
      : pkg.split('/')[0];
    for (const pkg of Object.keys(usedShared)) {
      if (__mfSeedKeys.includes(pkg)) continue;
      const packageName = __mfSeedPackageName(pkg);
      const rootIndex = __mfSeedKeys.indexOf(packageName);
      if (rootIndex === -1) {
        __mfSeedKeys.push(pkg);
        continue;
      }
      let insertIndex = rootIndex;
      while (
        insertIndex > 0 &&
        __mfSeedPackageName(__mfSeedKeys[insertIndex - 1]) === packageName &&
        __mfSeedKeys[insertIndex - 1] !== packageName
      ) {
        insertIndex--;
      }
      __mfSeedKeys.splice(insertIndex, 0, pkg);
    }
    var __mfSeedLocalShared = async (seedKeys) => {
      for (const pkg of seedKeys) {
        const share = usedShared[pkg];
        const cacheDescriptor = __mfGetSharedCacheDescriptor(pkg, share.shareConfig?.singleton, share.version, share.scope);
        if (
          share.shareConfig?.import === false ||
          Boolean(share.treeShaking) ||
          __mfReadSharedCache(__mfModuleCache.share, cacheDescriptor) !== undefined
        ) {
          continue;
        }
        const singletonCacheDescriptor = __mfGetSharedCacheDescriptor(pkg, true, share.version, share.scope);
        const singletonModule = __mfReadSharedCache(__mfModuleCache.share, singletonCacheDescriptor);
        if (singletonModule !== undefined) {
          __mfWriteSharedCache(
            __mfModuleCache.share,
            cacheDescriptor,
            singletonModule,
            __mfReadSharedCacheOwner(__mfModuleCache.share, singletonCacheDescriptor)
          );
          continue;
        }
        const factory = await share.get();
        const mod = typeof factory === "function" ? factory() : factory;
        const resolved = await Promise.resolve(mod);
        ${normalizeRuntimeShareCode}
        const normalizedModule = __mfNormalizeRuntimeShare(resolved);
        const exportModule = normalizedModule === resolved ? {...resolved} : normalizedModule;
        if (exportModule.__esModule !== true) Object.defineProperty(exportModule, "__esModule", {
          value: true,
          enumerable: false
        });
        __mfWriteSharedCache(__mfModuleCache.share, cacheDescriptor, exportModule, mfName);
      }
    };
    const __mfIsRuntimeOnlySharePending = (pkg) => {
      const share = usedShared[pkg];
      if (!share.treeShaking && share.shareConfig?.import !== false) return false;
      const cacheDescriptor = __mfGetSharedCacheDescriptor(
        pkg,
        share.shareConfig?.singleton,
        share.version,
        share.scope
      );
      return share.treeShaking
        ? (
            __mfReadTreeShakingSharedSelection(
              __mfModuleCache.share,
              cacheDescriptor,
              mfName
            ) === undefined &&
            __mfReadSharedCache(__mfModuleCache.share, cacheDescriptor) === undefined
          )
        : __mfReadSharedCache(__mfModuleCache.share, cacheDescriptor) === undefined;
    };
    const __mfNeedsPreInitSeedBarrier = (pkg) => {
      const share = usedShared[pkg];
      const cacheDescriptor = __mfGetSharedCacheDescriptor(
        pkg,
        share.shareConfig?.singleton,
        share.version,
        share.scope
      );
      const cachedShare = share.treeShaking
        ? (
            __mfReadTreeShakingSharedSelection(
              __mfModuleCache.share,
              cacheDescriptor,
              mfName
            ) ?? __mfReadSharedCache(__mfModuleCache.share, cacheDescriptor)
          )
        : __mfReadSharedCache(__mfModuleCache.share, cacheDescriptor);
      if (cachedShare !== undefined) return false;
      if (share.treeShaking || share.shareConfig?.import === false) return true;
      if (!share.shareConfig?.singleton) return false;
      if (typeof __mfSelectExternalSharedProvider !== 'function') return false;
      return Boolean(__mfSelectExternalSharedProvider(
        initialShared[pkg],
        pkg,
        share,
        ${JSON.stringify(shareStrategy)}
      ));
    };
    const __mfFirstRuntimeSeedBarrierIndex = __mfSeedKeys.findIndex(
      __mfNeedsPreInitSeedBarrier
    );
    const __mfImmediateSeedKeys = __mfFirstRuntimeSeedBarrierIndex === -1
      ? __mfSeedKeys
      : __mfSeedKeys.slice(0, __mfFirstRuntimeSeedBarrierIndex);
    var __mfDeferredSeedKeys = __mfFirstRuntimeSeedBarrierIndex === -1
      ? []
      : __mfSeedKeys.slice(__mfFirstRuntimeSeedBarrierIndex);
    await __mfSeedLocalShared(__mfImmediateSeedKeys);`;
}

function getBrowserImportPath(importPath: string) {
  if (/^(?:[a-zA-Z]:[\\/]|\/)/.test(importPath) && !importPath.startsWith('/@')) {
    return `/@fs/${importPath}`;
  }
  return importPath;
}

function getHostAutoInitSharedSeedItems(options?: NormalizedModuleFederationOptions) {
  const resolvedOptions = options ?? getNormalizeModuleFederationOptions();
  return getOrderedUsedShares(options)
    .map((pkg) => ({ pkg, shareItem: getShareItemForPreload(pkg, resolvedOptions) }))
    .filter(({ shareItem }) => shareItem?.shareConfig?.import === false)
    .sort((a, b) => {
      const priority = (pkg: string) => (pkg === 'vue' ? 0 : pkg === 'pinia' ? 1 : 2);
      const aIsLocal = !!getLocalProviderImportPath(a.pkg);
      const bIsLocal = !!getLocalProviderImportPath(b.pkg);
      return (
        priority(a.pkg) - priority(b.pkg) ||
        Number(aIsLocal) - Number(bIsLocal) ||
        a.pkg.localeCompare(b.pkg)
      );
    });
}

function generateHostAutoInitSharedCacheSeedCode(
  command = 'build',
  options?: NormalizedModuleFederationOptions
) {
  // In build mode, skip seeding for import:false modules. The bundler would
  // attempt to resolve their transitive dependencies which may not be
  // accessible (e.g. under pnpm strict mode). The runtime.loadShare() loop
  // that follows will handle acquiring these modules at runtime instead.
  if (command === 'build') return '';

  const resolvedOptions = options ?? getNormalizeModuleFederationOptions();
  return getHostAutoInitSharedSeedItems(options)
    .map(({ pkg, shareItem }) => {
      if (!shareItem) return null;
      const importPath = getBrowserImportPath(getDirectSharedCacheSeedImportPath(pkg, shareItem));
      return generateSharedCacheSeedItem(pkg, shareItem, importPath, resolvedOptions);
    })
    .filter((item) => item !== null)
    .join('\n');
}

const REMOTE_ENTRY_ID = 'virtual:mf-REMOTE_ENTRY_ID';

export function getRemoteEntryId(
  options: Pick<NormalizedModuleFederationOptions, 'internalName' | 'filename'>
) {
  const scopedKey = `${options.internalName}__${options.filename}`.replace(/[^a-zA-Z0-9_-]/g, '_');
  return `${REMOTE_ENTRY_ID}:${scopedKey}`;
}
// SSR-only plugins import Node.js modules and must not be statically imported
// in the browser remote entry — doing so causes fileURLToPath / bare-specifier
// errors in the browser bundle. They are dynamically imported on the server only.
const SSR_ONLY_PLUGIN_SPECIFIERS = new Set(['@module-federation/vite/ssrEntryLoader']);
const isSsrOnlyPlugin = (importStatement: string) =>
  [...SSR_ONLY_PLUGIN_SPECIFIERS].some((s) => importStatement.includes(s));
const getSsrOnlyPluginSpecifier = (importStatement: string): string | undefined =>
  [...SSR_ONLY_PLUGIN_SPECIFIERS].find((s) => importStatement.includes(s));

function generateTreeShakingSharedResolutionCode(enabled: boolean): string {
  if (!enabled) return 'const __mfResolveTreeShakingShared = async () => {};';
  return `
    // Resolve tree-enabled shares through the Runtime after all providers have
    // registered. Partial providers are stored with their export coverage and
    // never occupy generic/legacy cache keys, which are reserved for complete
    // modules only.
    const __mfResolveTreeShakingShared = async (pkg, share) => {
      const treeShaking = share.treeShaking;
      if (!treeShaking) return;
      try {
        const factory = await initRes.loadShare(pkg, {
          customShareInfo: {
            shareConfig: share.shareConfig,
            treeShaking: {
              mode: treeShaking.mode,
              status: treeShaking.status,
              usedExports: treeShaking.usedExports,
            },
          },
        });
        if (factory === false) return;
        const mod = typeof factory === "function" ? factory() : factory;
        const resolved = await Promise.resolve(mod);
        ${normalizeRuntimeShareCode}
        const cacheDescriptor = __mfGetSharedCacheDescriptor(pkg, share.shareConfig?.singleton, share.version, share.scope);
        const normalizedShared = __mfNormalizeRuntimeShare(resolved);
        const providedExports = treeShaking.providedExports ?? treeShaking.usedExports ?? [];
        const hasPartialProvider =
          ((treeShaking.mode === "runtime-infer" && treeShaking.status !== 0) ||
            treeShaking.status === 2);
        if (hasPartialProvider) {
          __mfWriteTreeShakingSharedCache(
            __mfModuleCache.share,
            cacheDescriptor,
            providedExports,
            normalizedShared
          );
          __mfWriteTreeShakingSharedSelection(
            __mfModuleCache.share,
            cacheDescriptor,
            mfName,
            normalizedShared
          );
        } else {
          __mfWriteSharedCache(__mfModuleCache.share, cacheDescriptor, normalizedShared);
        }
      } catch (e) {
        console.warn('[Module Federation] Failed to load tree-shaken shared module', pkg, e);
      }
    };`;
}

export const treeShakingResolveShareBodyCode = `const consumerTreeShaking = args.shareInfo?.treeShaking;
      if (consumerTreeShaking?.mode !== "runtime-infer") return args;
      const requiredExports = consumerTreeShaking.usedExports;
      if (!Array.isArray(requiredExports)) return args;

      const originalResolver = args.resolver;
      args.resolver = () => {
        const resolved = originalResolver();
        if (!resolved?.useTreesShaking) return resolved;

        const selectedExports = resolved.shared?.treeShaking?.usedExports;
        const selectedMatches = Array.isArray(selectedExports) &&
          requiredExports.every((name) => selectedExports.includes(name));
        if (selectedMatches) return resolved;

        // Runtime 2.7 prefers a tree provider by version before checking export
        // coverage. Prefer this consumer's own compatible provider when one is
        // available; otherwise retain the selected version but use its complete
        // top-level getter.
        const localExports = consumerTreeShaking.providedExports;
        const localMatches = typeof consumerTreeShaking.get === "function" &&
          Array.isArray(localExports) &&
          requiredExports.every((name) => localExports.includes(name));
        if (localMatches) {
          return { shared: args.shareInfo, useTreesShaking: true };
        }
        return { shared: resolved.shared, useTreesShaking: false };
      };
      return args;`;

function generateTreeShakingSnapshotPluginCode(enabled: boolean): string {
  if (!enabled) return '';
  return `
  const __mfTreeShakingSnapshotPlugin = () => ({
    name: "vite-tree-shaking-snapshot-plugin",
    resolveShare(args) {
      ${treeShakingResolveShareBodyCode}
    },
    beforeInit(args) {
      const { userOptions, origin, options: registeredOptions } = args;
      const version = userOptions.version || registeredOptions.version;
      const hostSnapshot = runtimeGlobal.getGlobalSnapshotInfoByModuleInfo({
        name: origin.name,
        version,
      });
      if (!hostSnapshot || !("shared" in hostSnapshot)) return args;

      const candidates = [];
      const appendShared = (records) => {
        for (const [pkgName, value] of Object.entries(records || {})) {
          const values = Array.isArray(value) ? value : [value];
          for (const shared of values) candidates.push([pkgName, shared]);
        }
      };
      appendShared(userOptions.shared);
      appendShared(registeredOptions.shared);

      for (const [pkgName, shared] of candidates) {
        const treeShaking = shared?.treeShaking;
        if (!treeShaking || treeShaking.mode !== "server-calc") continue;
        const shareSnapshot = hostSnapshot.shared.find((item) => item.sharedName === pkgName);
        if (!shareSnapshot || typeof shareSnapshot.treeShakingStatus !== "number") continue;
        const {
          secondarySharedTreeShakingEntry: entry,
          secondarySharedTreeShakingName: name,
          treeShakingStatus: status,
          usedExports,
          fallbackType,
        } = shareSnapshot;

        // A CALCULATED snapshot without a loadable secondary entry is not safe:
        // retain UNKNOWN so the Runtime chooses the complete top-level getter.
        if (status === 2 && (!entry || !name)) continue;
        if (Array.isArray(usedExports)) {
          treeShaking.usedExports = usedExports;
          treeShaking.providedExports = usedExports;
        }
        if (entry && name) {
          const fullFallbackGet = shared.get;
          treeShaking.get = async () => {
            try {
              const shareEntry = await getRemoteEntry({
                origin,
                remoteInfo: {
                  name,
                  entry,
                  type: fallbackType || "global",
                  entryGlobalName: name,
                  shareScope: "default",
                },
              });
              if (!shareEntry) throw new Error("Tree-shaken shared entry did not load");
              if (typeof shareEntry.init === "function") {
                await shareEntry.init(origin);
              }
              return shareEntry.get();
            } catch (error) {
              if (typeof fullFallbackGet === "function") return fullFallbackGet();
              throw error;
            }
          };
        }
        treeShaking.status = status;
      }
      return args;
    },
  });`;
}

export function generateRemoteEntry(
  options: NormalizedModuleFederationOptions,
  virtualExposesId = getVirtualExposesId(options),
  command = 'build'
): string {
  const needsSharedProviderSelectionHelper = Object.keys(options.shared ?? {}).length > 0;
  const hasTreeShakingShared = Object.values(options.shared ?? {}).some(
    (share) => !!share?.shareConfig.treeShaking
  );
  const hasEagerShared = Object.values(options.shared ?? {}).some(
    (share) => share?.shareConfig.eager === true && share.shareConfig.import !== false
  );
  const hasMultipleShareScopes = Array.isArray(options.shareScope);
  const runtimeImports = [
    'init as runtimeInit',
    'loadRemote',
    ...(hasTreeShakingShared ? ['getRemoteEntry'] : []),
  ].join(', ');
  const runtimeHelperImports = [
    ...(hasTreeShakingShared ? ['global as runtimeGlobal'] : []),
    ...(needsSharedProviderSelectionHelper ? ['share as runtimeShare'] : []),
  ];
  const pluginImportNames = options.runtimePlugins.map((p, i) => {
    if (typeof p === 'string') {
      return [`$runtimePlugin_${i}`, `import $runtimePlugin_${i} from "${p}";`, `undefined`];
    } else {
      return [
        `$runtimePlugin_${i}`,
        `import $runtimePlugin_${i} from "${p[0]}";`,
        serializeRuntimeOptions(p[1]),
      ];
    }
  });
  const initializeSharingCode = hasMultipleShareScopes
    ? `for (const shareScopeName of shareScopeNamesToInitialize) {
      try {
        await retrySharedInit(async () => {
          await Promise.all(await initRes.initializeSharing(shareScopeName, {
            strategy: '${options.shareStrategy}',
            from: "build",
            initScope
          }));
        });
      } catch (e) {
        console.error('[Module Federation]', e)
      }
    }`
    : `try {
      await retrySharedInit(async () => {
        await Promise.all(await initRes.initializeSharing('${options.shareScope}', {
          strategy: '${options.shareStrategy}',
          from: "build",
          initScope
        }));
      });
    } catch (e) {
      console.error('[Module Federation]', e)
    }`;

  return `
  // Shim Vue HMR runtime for dev-compiled components loaded by a non-Vite host.
  // When a remote is served by a Vite dev server, Vue's SFC compiler injects HMR
  // hooks that reference __VUE_HMR_RUNTIME__. This global only exists on pages
  // served by Vite's client runtime. When a production host loads the remote,
  // the HMR calls would throw. This no-op shim prevents that.
  if (typeof __VUE_HMR_RUNTIME__ === 'undefined') {
    globalThis.__VUE_HMR_RUNTIME__ = { createRecord() {}, rerender() {}, reload() {} };
  }
  import {${runtimeImports}} from "@module-federation/runtime";
  ${
    hasEagerShared
      ? `import * as __mfLocalSharedImportMap from "${getLocalSharedImportMapPath(options)}";`
      : ''
  }
  ${
    runtimeHelperImports.length
      ? `import {${runtimeHelperImports.join(', ')}} from "@module-federation/runtime/helpers";`
      : ''
  }
  ${pluginImportNames
    .filter((item) => !isSsrOnlyPlugin(item[1]))
    .map((item) => item[1])
    .join('\n')}
  ${
    command === 'build'
      ? getRuntimeInitResolveBootstrapCode(
          false,
          options ? getRuntimeInitStatusImportId(options) : undefined
        )
      : getRuntimeInitBootstrapCode(
          false,
          options ? getRuntimeInitStatusImportId(options) : undefined
        ) + '\n  const { initResolve } = globalThis[globalKey];'
  }
  ${getRuntimeModuleCacheBootstrapCode()}
  const initTokens = {}
  const shareScopeNames = Array.isArray(${JSON.stringify(options.shareScope)}) ? ${JSON.stringify(options.shareScope)} : [${JSON.stringify(options.shareScope)}]
  const shareScopeName = ${JSON.stringify(
    hasMultipleShareScopes ? options.shareScope[0] : options.shareScope
  )}
  const mfName = ${JSON.stringify(options.name)}
  let localSharedImportMapPromise
  let exposesMapPromise
  const shouldRetrySharedInitError = ${command !== 'build'} && ((error) => {
    const message = String((error && error.message) || error || '');
    return message.includes('Importing a module script failed') ||
      message.includes('Failed to fetch') ||
      message.includes('Load failed') ||
      message.includes('Outdated Optimize Dep');
  });
  const waitSharedInitRetry = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
  async function retrySharedInit(fn) {
    for (let attempt = 0; ; attempt++) {
      try {
        return await fn();
      } catch (e) {
        const canRetry = typeof shouldRetrySharedInitError === 'function' && shouldRetrySharedInitError(e);
        if (!canRetry || attempt >= 19) throw e;
        await waitSharedInitRetry(250);
      }
    }
  }
  ${generateTreeShakingSnapshotPluginCode(hasTreeShakingShared)}
  ${needsSharedProviderSelectionHelper ? sharedProviderSelectionHelperCode : ''}
  ${needsSharedProviderSelectionHelper ? externalSharedProviderSelectionHelperCode : ''}

  async function getLocalSharedImportMap() {
    ${hasEagerShared ? 'return __mfLocalSharedImportMap;' : ''}
    ${
      hasEagerShared
        ? ''
        : `if (!localSharedImportMapPromise) {
      localSharedImportMapPromise = retrySharedInit(() => import("${getLocalSharedImportMapPath(options)}"))
        .catch((e) => { localSharedImportMapPromise = undefined; throw e; });
    }
    return localSharedImportMapPromise`
    }
  }

  async function getExposesMap() {
    if (!exposesMapPromise) {
      exposesMapPromise = retrySharedInit(() => import("${virtualExposesId}"))
        .then((mod) => mod.default ?? mod)
        .catch((e) => { exposesMapPromise = undefined; throw e; });
    }
    return exposesMapPromise
  }

  async function init(shared = {}, initScope = []) {
    ${sharedCacheHelperCode}
    const getShareScope = (scopeName) => ${hasMultipleShareScopes} ? (shared?.[scopeName] || {}) : shared;
    const getShareScopeNames = (share) => {
      const configuredScopes = Array.isArray(share?.scope) ? share.scope : [share?.scope || shareScopeName];
      if (!${hasMultipleShareScopes}) return configuredScopes;
      return [...new Set([...configuredScopes, ...shareScopeNames])];
    };
    const getShareScopeName = (pkg, share) => {
      for (const scopeName of getShareScopeNames(share)) {
        if (getShareScope(scopeName)?.[pkg]) return scopeName;
      }
      return shareScopeName;
    };
    const getShareVersions = (pkg, share) => {
      for (const scopeName of getShareScopeNames(share)) {
        const versions = getShareScope(scopeName)?.[pkg];
        if (versions) return versions;
      }
      return getShareScope(shareScopeName)?.[pkg];
    };
    const federationInstances = globalThis.__FEDERATION__?.__INSTANCES__ || [];
    const initRootName = initScope.find((token) => token?.from)?.from;
    const scopeRoot = federationInstances.find((instance) =>
      instance?.options?.name === initRootName &&
      ${
        hasMultipleShareScopes
          ? 'shareScopeNames.some((scopeName) => instance?.shareScopeMap?.[scopeName] === getShareScope(scopeName))'
          : `instance?.shareScopeMap?.['${options.shareScope}'] === shared`
      }
    ) || federationInstances.find((instance) =>
      instance?.options?.name !== mfName &&
      ${
        hasMultipleShareScopes
          ? 'shareScopeNames.some((scopeName) => instance?.shareScopeMap?.[scopeName] === getShareScope(scopeName))'
          : `instance?.shareScopeMap?.['${options.shareScope}'] === shared`
      }
    );
    const initialShared = Object.create(null);
    ${
      hasMultipleShareScopes
        ? `for (const scopeName of shareScopeNames) {
      for (const [pkg, versions] of Object.entries(getShareScope(scopeName))) {
        if (initialShared[pkg]) continue;
        const initialVersions = initialShared[pkg] = Object.create(null);
        for (const [version, provider] of Object.entries(versions)) {
          initialVersions[version] = Object.assign({}, provider);
        }
      }
    }`
        : `for (const [pkg, versions] of Object.entries(shared)) {
      const initialVersions = initialShared[pkg] = Object.create(null);
      for (const [version, provider] of Object.entries(versions)) {
        // Runtime registration mutates provider records in-place, notably their origin.
        // Preserve the parent-visible provider and its original provenance.
        initialVersions[version] = Object.assign({}, provider);
      }
    }`
    }
    const {usedShared, usedRemotes} = await getLocalSharedImportMap()
    // handling circular init calls before an external provider can re-enter this container
    ${
      hasMultipleShareScopes
        ? `const shareScopeNamesToInitialize = [];
    for (const shareScopeName of shareScopeNames) {
      let initToken = initTokens[shareScopeName];
      if (!initToken) initToken = initTokens[shareScopeName] = { from: mfName };
      if (initScope.indexOf(initToken) >= 0) continue;
      initScope.push(initToken);
      shareScopeNamesToInitialize.push(shareScopeName);
    }
    if (shareScopeNamesToInitialize.length === 0) return;`
        : `var initToken = initTokens[shareScopeName];
    if (!initToken)
      initToken = initTokens[shareScopeName] = { from: mfName };
    if (initScope.indexOf(initToken) >= 0) return;
    initScope.push(initToken);`
    }
    ${normalizeRuntimeShareCode}
    const __browserPlugins = [${pluginImportNames
      .filter((item) => !isSsrOnlyPlugin(item[1]))
      .map((item) => `${item[0]}(${item[2]})`)
      .join(', ')}];
    const __ssrPlugins = typeof globalThis.window === 'undefined'
      ? await Promise.all([${pluginImportNames
        .filter((item) => isSsrOnlyPlugin(item[1]))
        .map((item) => {
          const specifier = getSsrOnlyPluginSpecifier(item[1])!;
          const opts = item[2];
          return `import(${JSON.stringify(specifier)}).then(m => (m.default ?? m)(${opts}))`;
        })
        .join(', ')}])
      : [];
    const __mfRuntimeShareLoadIdKey = "__mf_vite_runtime_share_load_id__";
    let __mfRuntimeShareLoadId = 0;
    const __mfRuntimeShareSelections = new Map();
    const __mfRuntimeShareLifecycles = new Map();
    const initRes = runtimeInit({
      name: mfName,
      remotes: ${options.shareStrategy === 'loaded-first' ? '[]' : 'usedRemotes'},
      shared: usedShared,
      plugins: [__mfSharePinLifecyclePlugin(), ${hasTreeShakingShared ? '__mfTreeShakingSnapshotPlugin(),' : ''} ...__browserPlugins, ...__ssrPlugins],
      ${options.shareStrategy ? `shareStrategy: '${options.shareStrategy}'` : ''}
    });
    ${
      hasMultipleShareScopes
        ? `for (const shareScopeName of shareScopeNamesToInitialize) {
      const scopeShare = getShareScope(shareScopeName);
      initRes.initShareScopeMap(shareScopeName, scopeShare);
    }`
        : `initRes.initShareScopeMap('${options.shareScope}', shared);`
    }
    function __mfSharePinLifecyclePlugin() {
      return {
        name: "vite-share-pin-lifecycle-plugin",
        resolveShare(args) {
          const loadId = args.shareInfo?.[__mfRuntimeShareLoadIdKey];
          const lifecycle = loadId === undefined
            ? undefined
            : __mfRuntimeShareLifecycles.get(loadId);
          if (!lifecycle) return args;
          const defaultResolver = args.resolver;
          args.resolver = (...resolverArgs) => {
            lifecycle.pinned.reapply();
            return defaultResolver(...resolverArgs);
          };
          lifecycle.pinned.reveal();
          return args;
        }
      };
    }
    const runtimeResolveShareHook = initRes.sharedHandler.hooks.lifecycle.resolveShare;
    const __mfRuntimeProviderOrigins = new WeakMap();
    runtimeResolveShareHook.on((args) => {
      const loadId = args.shareInfo?.[__mfRuntimeShareLoadIdKey];
      const resolver = args.resolver;
      if (typeof resolver !== "function") return args;
      const instrumentedResolver = (...resolverArgs) => {
        const resolved = resolver(...resolverArgs);
        const selectedProvider = resolved?.shared;
        if (
          selectedProvider &&
          (typeof selectedProvider === "object" || typeof selectedProvider === "function") &&
          !__mfRuntimeProviderOrigins.has(selectedProvider)
        ) {
          __mfRuntimeProviderOrigins.set(selectedProvider, { from: selectedProvider.from });
        }
        if (loadId !== undefined && selectedProvider) {
          __mfRuntimeShareSelections.set(loadId, selectedProvider);
        }
        return resolved;
      };
      args.resolver = instrumentedResolver;
      return args;
    });
    const __mfPinSharedProvider = (versionMap, version, currentProvider, provider) => {
      if (!versionMap || versionMap[version] !== currentProvider) return undefined;
      const pinnedProvider = Object.assign({}, provider, {
        version: provider.version ?? version,
        scope: provider.scope ?? currentProvider?.scope ?? ${JSON.stringify(
          hasMultipleShareScopes ? options.shareScope : [options.shareScope]
        )},
        strategy: 'loaded-first'
      });
      const providerFrom = provider.from;
      versionMap[version] = pinnedProvider;
      const isCurrentProviderActive = () => currentProvider === undefined
        ? versionMap[version] === undefined
        : versionMap[version] === currentProvider;
      return {
        provider: pinnedProvider,
        reveal() {
          if (versionMap[version] !== pinnedProvider) return false;
          if (currentProvider === undefined) delete versionMap[version];
          else versionMap[version] = currentProvider;
          return true;
        },
        reapply() {
          if (!isCurrentProviderActive()) return false;
          versionMap[version] = pinnedProvider;
          return true;
        },
        release(loaded, selected = true) {
          provider.from = providerFrom;
          if (versionMap[version] !== pinnedProvider) {
            return !selected && isCurrentProviderActive();
          }
          if (!selected) {
            if (currentProvider === undefined) delete versionMap[version];
            else versionMap[version] = currentProvider;
            return true;
          }
          if (!loaded) {
            if (currentProvider === undefined) delete versionMap[version];
            else versionMap[version] = currentProvider;
            return false;
          }
          pinnedProvider.from = providerFrom;
          if (loaded && pinnedProvider.lib) pinnedProvider.loaded = true;
          if (provider.strategy === undefined) delete pinnedProvider.strategy;
          else pinnedProvider.strategy = provider.strategy;
          return true;
        }
      };
    };
    const __mfSnapshotSharedProviders = (versionMap) => (
      Object.entries(versionMap || {}).map(([version, provider]) => ({
        provider,
        version,
        from: provider.from,
        registered: true
      }))
    );
    const __mfMatchLoadedSharedProvider = (providerSelections, factory) => {
      if (factory === undefined) return undefined;
      let match;
      for (const selection of providerSelections) {
        const provider = selection.provider;
        const directProvider = provider.treeShaking || provider;
        if (
          selection.loadedFactory !== factory &&
          provider.lib !== factory &&
          directProvider.lib !== factory
        ) continue;
        if (match) return undefined;
        match = selection;
      }
      return match;
    };
    const __mfLoadRuntimeShare = async (pkg, shareConfig, pinned) => {
      const loadId = ++__mfRuntimeShareLoadId;
      __mfRuntimeShareLifecycles.set(loadId, {
        pinned
      });
      try {
        const factory = await initRes.loadShare(pkg, {
          customShareInfo: {
            shareConfig,
            [__mfRuntimeShareLoadIdKey]: loadId
          }
        });
        return {
          factory: factory === false ? undefined : factory,
          selectedProvider: __mfRuntimeShareSelections.get(loadId)
        };
      } finally {
        __mfRuntimeShareSelections.delete(loadId);
        __mfRuntimeShareLifecycles.delete(loadId);
      }
    };
    const __mfLoadPinnedRuntimeShare = async (
      pkg,
      shareConfig,
      versionMap,
      version,
      currentProvider,
      provider,
      providerRegistered = true
    ) => {
      const providerFrom = provider.from;
      const pinned = __mfPinSharedProvider(
        versionMap,
        version,
        currentProvider,
        provider
      );
      if (!pinned) return undefined;
      let runtimeLoad;
      try {
        runtimeLoad = await __mfLoadRuntimeShare(pkg, shareConfig, pinned);
      } catch (error) {
        pinned.release(false);
        throw error;
      }
      const factory = runtimeLoad?.factory;
      if (factory === undefined) {
        pinned.release(false);
        return undefined;
      }
      const providerSelections = __mfSnapshotSharedProviders(versionMap);
      const directPinnedProvider = pinned.provider.treeShaking || pinned.provider;
      const pinnedMatchesFactory =
        pinned.provider.lib === factory || directPinnedProvider.lib === factory;
      if (!providerRegistered && pinnedMatchesFactory) {
        const pinnedSelectionIndex = providerSelections.findIndex(
          (selection) => selection.provider === pinned.provider
        );
        if (pinnedSelectionIndex !== -1) providerSelections.splice(pinnedSelectionIndex, 1);
      }
      if (!providerRegistered && !providerSelections.some((selection) => selection.provider === provider)) {
        providerSelections.push({
          provider,
          version,
          from: providerFrom,
          registered: false,
          loadedFactory: pinnedMatchesFactory ? factory : undefined
        });
      }
      const runtimeSelectedProvider =
        !providerRegistered &&
        runtimeLoad.selectedProvider === pinned.provider &&
        pinnedMatchesFactory
          ? provider
          : runtimeLoad.selectedProvider;
      if (
        runtimeSelectedProvider &&
        !providerSelections.some((selection) => selection.provider === runtimeSelectedProvider)
      ) {
        const runtimeProviderOrigin = __mfRuntimeProviderOrigins.get(runtimeSelectedProvider);
        const selectedVersion = typeof runtimeSelectedProvider.version === "string" && runtimeSelectedProvider.version
          ? runtimeSelectedProvider.version
          : version;
        providerSelections.push({
          provider: runtimeSelectedProvider,
          version: selectedVersion,
          from: runtimeProviderOrigin ? runtimeProviderOrigin.from : runtimeSelectedProvider.from,
          registered: versionMap?.[selectedVersion] === runtimeSelectedProvider,
          loadedFactory: factory
        });
      }
      const selection = providerSelections.find(
        (candidate) => candidate.provider === runtimeSelectedProvider
      ) ?? __mfMatchLoadedSharedProvider(providerSelections, factory);
      const providerStayedActive = pinned.release(
        true,
        selection?.provider === pinned.provider
      );
      if (!providerStayedActive || !selection) return undefined;
      const runtimeProviderOrigin = __mfRuntimeProviderOrigins.get(selection.provider);
      selection.from = selection.provider === provider
        ? providerFrom
        : runtimeProviderOrigin
          ? runtimeProviderOrigin.from
          : selection.provider.from;
      if (runtimeProviderOrigin) selection.provider.from = runtimeProviderOrigin.from;
      const mod = typeof factory === "function" ? factory() : factory;
      const resolved = await Promise.resolve(mod);
      if (selection.registered && versionMap?.[selection.version] !== selection.provider) return undefined;
      return { provider: selection.provider, selection, resolved };
    };
    const bridgedProviders = new Set();
    const bridgeSelections = new Map();
    const __mfBridgeMaterializedProvider = async (pkg, usedShare, versionMap) => {
      const singleton = Boolean(usedShare.shareConfig?.singleton);
      if (singleton && '${options.shareStrategy}' !== 'loaded-first') return;
      if (usedShare.canLiveRebind === false) return;
      try {
        const provider = __mfSelectExternalSharedProvider(
          versionMap,
          pkg,
          usedShare,
          '${options.shareStrategy}'
        );
        const providerEntry = __mfFindSharedProviderEntry(versionMap, provider);
        if (!providerEntry) return;
        const { version } = providerEntry;
        if (!singleton && version !== usedShare.version) return;
        if (
          !provider.lib &&
          !provider.loading &&
          !(provider.loaded && typeof provider.get === 'function')
        ) return;
        const usedCacheDescriptor = __mfGetSharedCacheDescriptor(
          pkg,
          singleton,
          usedShare.version,
          usedShare.scope
        );
        if (__mfReadSharedCache(__mfModuleCache.share, usedCacheDescriptor) !== undefined) return;
        const liveVersionMap = ${
          hasMultipleShareScopes ? 'getShareVersions(pkg, usedShare)' : 'shared[pkg]'
        };
        const liveProvider = liveVersionMap?.[version];
        if (providerEntry.registered && !__mfMatchesSharedProvider(liveProvider, provider)) return;
        let loadedShare;
        ${
          options.shareStrategy === 'loaded-first'
            ? `loadedShare = await __mfLoadPinnedRuntimeShare(
            pkg,
            usedShare.shareConfig,
            liveVersionMap,
            version,
            liveProvider,
            provider,
            providerEntry.registered
          );`
            : `// Runtime loadShare() implicitly initializes version-first remotes without
          // this container's outer initScope. Materialized providers are already active,
          // so resolve them directly and keep remote initialization on the guarded path.
          let directFactory = provider.lib;
          if (!directFactory && provider.loading) directFactory = await provider.loading;
          if (!directFactory && provider.loaded && typeof provider.get === 'function') {
            directFactory = await provider.get();
          }
          if (!directFactory) return;
          const directModule = typeof directFactory === "function" ? directFactory() : directFactory;
          const directResolved = await Promise.resolve(directModule);
          const directProvider = providerEntry.registered ? liveProvider : provider;
          loadedShare = {
            provider: directProvider,
            selection: {
              provider: directProvider,
              version,
              from: provider.from,
              registered: providerEntry.registered
            },
            resolved: directResolved
          };`
        }
        const actualProvider = loadedShare?.provider;
        const actualSelection = loadedShare?.selection;
        if (!actualSelection) return;
        const resolved = loadedShare?.resolved;
        if (resolved === undefined) return;
        if (__mfReadSharedCache(__mfModuleCache.share, usedCacheDescriptor) !== undefined) return;
        ${
          options.shareStrategy === 'loaded-first'
            ? `if (
          actualSelection.registered &&
          liveVersionMap?.[actualSelection.version] !== actualProvider
        ) return;`
            : `if (
          actualSelection.registered &&
          liveVersionMap?.[actualSelection.version] !== actualProvider
        ) return;`
        }
        __mfWriteSharedCache(
          __mfModuleCache.share,
          usedCacheDescriptor,
          __mfNormalizeRuntimeShare(resolved),
          actualSelection.from
        );
        bridgedProviders.add(actualProvider);
      } catch (e) {
        console.error('[Module Federation] Failed to bridge materialized shared module "' + pkg + '"', e)
      }
    };
    const __mfBridgeExternalSharedProvider = async (
      pkg,
      usedShare,
      versionMap,
      passedVersionMap,
      expectedSelection
    ) => {
      try {
        const usedCacheDescriptor = __mfGetSharedCacheDescriptor(pkg, usedShare.shareConfig?.singleton, usedShare.version, usedShare.scope);
        const cachedShare = __mfReadSharedCache(__mfModuleCache.share, usedCacheDescriptor);
        const cachedShareOwner = __mfReadSharedCacheOwner(__mfModuleCache.share, usedCacheDescriptor);
        const selectedExternalProvider = __mfSelectExternalSharedProvider(
          versionMap,
          pkg,
          usedShare,
          '${options.shareStrategy}'
        );
        const selectedRuntimeProvider = selectedExternalProvider ||
          __mfSelectSharedProvider(versionMap, pkg, usedShare, '${options.shareStrategy}') ||
          usedShare;
        const providerEntry = __mfFindSharedProviderEntry(versionMap, selectedRuntimeProvider);
        if (!providerEntry) return;
        const selectedLocalProvider = __mfMatchesSharedProvider(selectedRuntimeProvider, usedShare);
        const { version } = providerEntry;
        const passedProvider = passedVersionMap?.[version];
        const resolvedExternalProvider = __mfResolveExternalSharedProvider(
          federationInstances,
          scopeRoot,
          ${hasMultipleShareScopes ? 'getShareScope(getShareScopeName(pkg, usedShare))' : 'shared'},
          ${
            hasMultipleShareScopes ? 'getShareScopeName(pkg, usedShare)' : `'${options.shareScope}'`
          },
          pkg,
          providerEntry,
          selectedExternalProvider,
          passedProvider,
          '${options.shareStrategy}'
        );
        if (!resolvedExternalProvider && !selectedLocalProvider) return;
        const { provider, scopeRootProvider } = resolvedExternalProvider || {
          provider: selectedRuntimeProvider,
          scopeRootProvider: undefined
        };
        // Non-singleton proxies may have already snapshotted their local exports while
        // seeding shared dependencies. Late cache replacement is safe only for the
        // live-bound singleton proxies.
        if (!usedShare.shareConfig?.singleton) return;
        if (usedShare.canLiveRebind === false) return;
        // Preserve a singleton already selected by another container. The bridge may
        // only replace the provisional local fallback seeded by this container.
        if (cachedShare !== undefined && cachedShareOwner !== mfName) return;
        // Registration can replace an unloaded same-version root provider in-place.
        // Pin the chosen provider while loadShare() runs its implicit registration.
        const liveVersionMap = ${
          hasMultipleShareScopes ? 'getShareVersions(pkg, usedShare)' : 'shared[pkg]'
        };
        const liveProvider = liveVersionMap?.[version];
        if (
          providerEntry.registered &&
          !scopeRootProvider &&
          !__mfMatchesSharedProvider(liveProvider, provider)
        ) return;
        const loadedShare = await __mfLoadPinnedRuntimeShare(
          pkg,
          usedShare.shareConfig,
          liveVersionMap,
          version,
          liveProvider,
          provider,
          providerEntry.registered && !selectedLocalProvider
        );
        const actualProvider = loadedShare?.provider;
        const actualSelection = loadedShare?.selection;
        if (!actualSelection) return;
        if (__mfMatchesSharedProvider(actualProvider, usedShare)) return;
        if (expectedSelection) {
          if (
            expectedSelection.version !== actualSelection.version ||
            !__mfMatchesSharedProvider({ from: actualSelection.from }, expectedSelection.provider)
          ) return;
        }
        if (bridgedProviders.has(actualProvider)) return;
        const resolved = loadedShare?.resolved;
        if (resolved === undefined) return;
        const latestCachedShare = __mfReadSharedCache(__mfModuleCache.share, usedCacheDescriptor);
        const latestCachedShareOwner = __mfReadSharedCacheOwner(__mfModuleCache.share, usedCacheDescriptor);
        if (latestCachedShare !== undefined && latestCachedShareOwner !== mfName) return;
        if (
          actualSelection.registered &&
          liveVersionMap?.[actualSelection.version] !== actualProvider
        ) return;
        if (!expectedSelection) {
          bridgeSelections.set(pkg, {
            version: actualSelection.version,
            provider: { from: actualSelection.from }
          });
        }
        bridgedProviders.add(actualProvider);
        const normalized = __mfNormalizeRuntimeShare(resolved);
        __mfWriteSharedCache(
          __mfModuleCache.share,
          usedCacheDescriptor,
          normalized,
          actualSelection.from
        );
      } catch (e) {
        console.error('[Module Federation] Failed to bridge external shared module "' + pkg + '"', e)
      }
    };
    for (const [pkg, usedShare] of Object.entries(usedShared)) {
      if (usedShare.treeShaking) continue;
      await __mfBridgeMaterializedProvider(pkg, usedShare, initialShared[pkg]);
    }
    for (const [pkg, share] of Object.entries(usedShared)) {
      if (share.treeShaking) continue;
      const cacheDescriptor = __mfGetSharedCacheDescriptor(pkg, share.shareConfig?.singleton, share.version, share.scope);
      if (__mfReadSharedCache(__mfModuleCache.share, cacheDescriptor) !== undefined) continue;
      const singletonCacheDescriptor = __mfGetSharedCacheDescriptor(pkg, true, share.version, share.scope);
      const singletonModule = __mfReadSharedCache(__mfModuleCache.share, singletonCacheDescriptor);
      if (singletonModule !== undefined) {
        __mfWriteSharedCache(
          __mfModuleCache.share,
          cacheDescriptor,
          singletonModule,
          __mfReadSharedCacheOwner(__mfModuleCache.share, singletonCacheDescriptor)
        );
      }
    }
    ${generateRuntimeSharedCacheSeedCode(options.shareStrategy)}
    ${initializeSharingCode}
    // Calling provider.get() marks a provider as loaded. Wait until the Runtime has
    // finalized normal same-version precedence before materializing an external share.
    for (const [pkg, usedShare] of Object.entries(usedShared)) {
      if (usedShare.treeShaking) continue;
      await __mfBridgeExternalSharedProvider(
        pkg,
        usedShare,
        ${hasMultipleShareScopes ? 'getShareVersions(pkg, usedShare)' : 'shared[pkg]'},
        initialShared[pkg],
        undefined
      );
    }
    try {
      const allInstances = globalThis.__FEDERATION__?.__SHARE__;
      const globalVersionsByPackage = Object.create(null);
      if (allInstances) {
        for (const [, scopes] of Object.entries(allInstances)) {
          for (const scopeName of shareScopeNames) {
            const scopeShare = scopes?.[scopeName];
            if (!scopeShare) continue;
            for (const [pkg, versionMap] of Object.entries(scopeShare)) {
            const usedShare = usedShared?.[pkg];
            const passedVersions = initialShared[pkg];
            const bridgeSelection = bridgeSelections.get(pkg);
            if (!usedShare) continue;
            if (!passedVersions) continue;
            if (!bridgeSelection) continue;
            if (usedShare.treeShaking) continue;
            const globalVersions = globalVersionsByPackage[pkg] || (globalVersionsByPackage[pkg] = Object.create(null));
            for (const [version, provider] of Object.entries(versionMap)) {
              if (!provider.lib) continue;
              if (bridgeSelection.version !== version) continue;
              if (!__mfMatchesSharedProvider(provider, bridgeSelection.provider)) continue;
              const passedProvider = passedVersions[version];
              const matchesPassedProvider = provider === passedProvider || (
                passedProvider?.from && provider.from === passedProvider.from
              );
              if (!matchesPassedProvider) continue;
              if (provider === usedShare || (usedShare.from && provider.from === usedShare.from)) continue;
              if (globalVersions[version] === undefined) globalVersions[version] = provider;
            }
            }
          }
        }
      }
      for (const [pkg, versionMap] of Object.entries(globalVersionsByPackage)) {
        await __mfBridgeExternalSharedProvider(
          pkg,
          usedShared[pkg],
          versionMap,
          initialShared[pkg],
          bridgeSelections.get(pkg)
        );
      }
    } catch (e) {
      console.error('[Module Federation] Failed to bridge external shared modules', e)
    }
    ${generateTreeShakingSharedResolutionCode(hasTreeShakingShared)}
    const __mfResolveImportFalseShared = async (pkg, share) => {
      const cacheDescriptor = __mfGetSharedCacheDescriptor(pkg, share.shareConfig?.singleton, share.version, share.scope);
      const cachedShare = share.treeShaking
        ? __mfReadTreeShakingSharedSelection(__mfModuleCache.share, cacheDescriptor, mfName)
        : __mfReadSharedCache(__mfModuleCache.share, cacheDescriptor);
      if (share.shareConfig?.import !== false || cachedShare !== undefined) return;
      ${normalizeRuntimeShareCode}
      const versionMap = ${hasMultipleShareScopes ? 'getShareVersions(pkg, share)' : 'shared?.[pkg]'};
      const provider = __mfSelectSharedProvider(
        versionMap,
        pkg,
        share,
        '${options.shareStrategy}'
      ) || share;
      const providerEntry = __mfFindSharedProviderEntry(versionMap, provider);
      if (!providerEntry) return;
      const { version } = providerEntry;
      const currentProvider = versionMap?.[version];
      const loadedShare = await __mfLoadPinnedRuntimeShare(
        pkg,
        share.shareConfig,
        versionMap,
        version,
        currentProvider,
        provider,
        providerEntry.registered && !__mfMatchesSharedProvider(provider, share)
      );
      const providerSelection = loadedShare?.selection;
      const actualProvider = loadedShare?.provider;
      const resolved = loadedShare?.resolved;
      if (!providerSelection) return;
      if (__mfMatchesSharedProvider(actualProvider, share)) return;
      if (resolved === undefined) return;
      const latestCachedShare = share.treeShaking
        ? __mfReadTreeShakingSharedSelection(__mfModuleCache.share, cacheDescriptor, mfName)
        : __mfReadSharedCache(__mfModuleCache.share, cacheDescriptor);
      if (latestCachedShare !== undefined) return;
      if (
        providerSelection.registered &&
        versionMap?.[providerSelection.version] !== actualProvider
      ) return;
      const normalizedShared = __mfNormalizeRuntimeShare(resolved);
      if (share.treeShaking) {
        const providedExports = share.treeShaking.providedExports ?? share.treeShaking.usedExports ?? [];
        __mfWriteTreeShakingSharedCache(
          __mfModuleCache.share,
          cacheDescriptor,
          providedExports,
          normalizedShared
        );
        __mfWriteTreeShakingSharedSelection(
          __mfModuleCache.share,
          cacheDescriptor,
          mfName,
          normalizedShared
        );
      } else {
        __mfWriteSharedCache(
          __mfModuleCache.share,
          cacheDescriptor,
          normalizedShared,
          providerSelection.from
        );
      }
    };
    // Resolve runtime-only dependencies and seed local fallbacks in dependency
    // order. Stop at an unresolved provider so its consumers cannot capture an
    // undefined or provisional singleton.
    for (const pkg of __mfDeferredSeedKeys) {
      const share = usedShared[pkg];
      if (__mfIsRuntimeOnlySharePending(pkg)) {
        if (share.treeShaking) {
          await __mfResolveTreeShakingShared(pkg, share);
        } else if (share.shareConfig?.import === false) {
          await __mfResolveImportFalseShared(pkg, share);
        }
      }
      if (__mfIsRuntimeOnlySharePending(pkg)) break;
      await __mfSeedLocalShared([pkg]);
    }
    initResolve(initRes)
    return initRes
  }

  async function getExposes(moduleName) {
    const exposesMap = await getExposesMap()
    if (!(moduleName in exposesMap)) throw new Error(\`[Module Federation] Module \${moduleName} does not exist in container.\`)
    if (__mfModuleCache.pendingShareLoads) {
      await Promise.all(__mfModuleCache.pendingShareLoads)
    }
    return (exposesMap[moduleName])().then(res => () => res)
  }
  export {
      init,
      getExposes as get
  }
  `;
}

/**
 * Inject entry file, automatically init when used as host,
 * and will not inject remoteEntry
 */
export const HOST_AUTO_INIT_TAG = '__H_A_I__';
interface HostAutoInitState {
  module: VirtualModule;
  remoteEntryId: string;
  command: string;
}

const hostAutoInitStates = new WeakMap<NormalizedModuleFederationOptions, HostAutoInitState>();
const legacyHostAutoInitState: HostAutoInitState = {
  module: new VirtualModule('hostAutoInit', HOST_AUTO_INIT_TAG),
  remoteEntryId: REMOTE_ENTRY_ID,
  command: 'build',
};

function getHostAutoInitState(options?: NormalizedModuleFederationOptions) {
  if (!options) return legacyHostAutoInitState;
  let state = hostAutoInitStates.get(options);
  if (!state) {
    const ownerKey = getLocalOwnerKey(options);
    state = {
      module: new VirtualModule('hostAutoInit', HOST_AUTO_INIT_TAG, '', ownerKey),
      remoteEntryId: REMOTE_ENTRY_ID,
      command: 'build',
    };
    hostAutoInitStates.set(options, state);
  }
  return state;
}

export function generateHostAutoInitCode(
  remoteEntryImport: string,
  _command = 'build',
  options?: NormalizedModuleFederationOptions
) {
  const resolvedOptions = options ?? getNormalizeModuleFederationOptions();
  const shouldPreloadShares = resolvedOptions.shareStrategy !== 'loaded-first';
  const hostInitShareOrder = JSON.stringify(getOrderedUsedShares(options));
  const cacheOwner = JSON.stringify(resolvedOptions.name);
  return `
    ${getRuntimeModuleCacheBootstrapCode()}
    let hostInitPromise;
    async function initHost() {
      if (!hostInitPromise) {
        hostInitPromise = (async () => {
          ${sharedCacheHelperCode}
          ${generateHostAutoInitSharedCacheSeedCode(_command, options)}
          const remoteEntry = await import(${remoteEntryImport});
          const runtime = await remoteEntry.init();
          const {usedShared} = await import("${getLocalSharedImportMapPath(options)}");
          ${normalizeRuntimeShareCode}
          ${
            shouldPreloadShares
              ? `
          const __mfHostInitShareOrder = ${hostInitShareOrder}
            .concat(Object.keys(usedShared).filter((pkg) => !${hostInitShareOrder}.includes(pkg)));
          for (const pkg of __mfHostInitShareOrder) {
            const share = usedShared[pkg];
            if (!share) continue;
            // remoteEntry.init resolves tree-enabled shares into the
            // coverage-aware cache. Never republish that selected partial under
            // a generic full-module key here.
            if (share.treeShaking) continue;
            const cacheDescriptor = __mfGetSharedCacheDescriptor(pkg, share.shareConfig?.singleton, share.version, share.scope);
            if (__mfReadSharedCache(__mfModuleCache.share, cacheDescriptor) !== undefined) {
              continue;
            }
            await runtime.loadShare(pkg, {
              customShareInfo: { shareConfig: share.shareConfig }
            }).then((factory) => {
              const mod = typeof factory === "function" ? factory() : factory;
              return Promise.resolve(mod).then((resolved) => {
                __mfWriteSharedCache(
                  __mfModuleCache.share,
                  cacheDescriptor,
                  __mfNormalizeRuntimeShare(resolved),
                  ${cacheOwner}
                );
              });
            });
          }
          `
              : ''
          }
          const __mfRemotePreloads = [];
          await Promise.all(__mfRemotePreloads);
          return runtime;
        })();
      }
      return hostInitPromise;
    }
    hostInitPromise = initHost();
    export { initHost, hostInitPromise };
    `;
}
export function writeHostAutoInit(
  remoteEntryId = REMOTE_ENTRY_ID,
  command = 'build',
  options?: NormalizedModuleFederationOptions
) {
  const state = getHostAutoInitState(options);
  state.remoteEntryId = remoteEntryId;
  state.command = command;
  state.module.writeSync(
    generateHostAutoInitCode(JSON.stringify(remoteEntryId), command, options),
    true
  );
}
export function refreshHostAutoInit(options?: NormalizedModuleFederationOptions) {
  try {
    const state = getHostAutoInitState(options);
    writeHostAutoInit(state.remoteEntryId, state.command, options);
  } catch {
    // Some isolated unit tests exercise share/remote plugins without
    // initializing normalized federation options.
  }
}
export function getHostAutoInitImportId(options?: NormalizedModuleFederationOptions) {
  return getHostAutoInitState(options).module.getImportId();
}
export function getHostAutoInitPath(options?: NormalizedModuleFederationOptions) {
  return getHostAutoInitState(options).module.getImportId();
}
