import {
  getNormalizeModuleFederationOptions,
  getNormalizeShareItem,
  isExplicitSharedKey,
  NormalizedModuleFederationOptions,
  ShareItem,
} from '../utils/normalizeModuleFederationOptions';
import {
  getInstalledPackageJson,
  getPackageName,
  getSharedCacheDescriptor,
  hasPackageDependency,
  packageNameEncode,
  sharedCacheHelperCode,
} from '../utils/packageUtils';
import { serializeRuntimeOptions } from '../utils/serializeRuntimeOptions';
import VirtualModule from '../utils/VirtualModule';
import { getVirtualExposesId } from './virtualExposes';
import { getUsedRemotesMap } from './virtualRemotes';
import {
  getRuntimeInitBootstrapCode,
  getRuntimeInitResolveBootstrapCode,
  getRuntimeModuleCacheBootstrapCode,
} from './virtualRuntimeInitStatus';
import {
  getConcreteSharedImportSource,
  getLocalProviderImportPath,
  getProjectResolvedImportPath,
  getSharedImportSource,
} from './virtualShared_preBuild';

let usedShares: Set<string> = new Set();
export function getUsedShares() {
  return usedShares;
}
export function addUsedShares(pkg: string) {
  usedShares.add(pkg);
}
const LOCAL_SHARED_IMPORT_MAP_ID = 'virtual:mf-localSharedImportMap';

export function getLocalSharedImportMapPath() {
  const { internalName, name } = getNormalizeModuleFederationOptions();
  return `${LOCAL_SHARED_IMPORT_MAP_ID}:${packageNameEncode(internalName || name)}`;
}

export function getResolvedLocalSharedImportMapId() {
  return `\0${getLocalSharedImportMapPath()}`;
}

let invalidateLocalSharedImportMap: (() => void) | undefined;
export function setLocalSharedImportMapInvalidator(invalidator: (() => void) | undefined) {
  invalidateLocalSharedImportMap = invalidator;
}

export function writeLocalSharedImportMap() {
  // The map is generated by the loader. Avoid rebuilding a large string every
  // time another shared module is discovered during resolution.
  invalidateLocalSharedImportMap?.();
}

function shouldUseDirectReactImport() {
  const isVinext = hasPackageDependency('vinext');
  const isAstro = hasPackageDependency('astro');
  return isVinext || isAstro;
}

function getLocalSharedPackagePath(pkg: string, shareItem: ShareItem) {
  const useDirectReactImport = shouldUseDirectReactImport();
  if (useDirectReactImport && pkg === 'react') return 'react';

  return (
    getConcreteSharedImportSource(pkg, shareItem) ||
    getLocalProviderImportPath(pkg) ||
    getSharedImportSource(pkg, shareItem)
  );
}

function getDirectSharedCacheSeedImportPath(pkg: string, shareItem: ShareItem) {
  return (
    getConcreteSharedImportSource(pkg, shareItem) ||
    getProjectResolvedImportPath(pkg) ||
    getLocalProviderImportPath(pkg) ||
    pkg
  );
}

export function generateLocalSharedImportMap() {
  const useDirectReactImport = shouldUseDirectReactImport();
  const options = getNormalizeModuleFederationOptions();

  return `
    import {loadShare} from "@module-federation/runtime";
    const importMap = {
      ${Array.from(getUsedShares())
        .sort()
        .map((pkg) => {
          const shareItem = getNormalizeShareItem(pkg);
          return `
        ${JSON.stringify(pkg)}: async () => {
          ${
            shareItem?.shareConfig.import === false
              ? `throw new Error(\`[Module Federation] Shared module '\${${JSON.stringify(pkg)}}' must be provided by host\`);`
              : `let pkg = await import(${JSON.stringify(getLocalSharedPackagePath(pkg, shareItem))});
            return pkg;`
          }
        }
      `;
        })
        .join(',')}
    }
      const usedShared = {
      ${Array.from(getUsedShares())
        .sort()
        .map((key) => {
          const shareItem = getNormalizeShareItem(key);
          if (!shareItem) return null;
          return `
          ${JSON.stringify(key)}: {
            name: ${JSON.stringify(key)},
            version: ${JSON.stringify(shareItem.version)},
            scope: [${JSON.stringify(shareItem.scope)}],
            loaded: false,
            from: ${JSON.stringify(options.name)},
            async get () {
              if (${shareItem.shareConfig.import === false}) {
                throw new Error(\`[Module Federation] Shared module '\${${JSON.stringify(key)}}' must be provided by host\`);
              }
              usedShared[${JSON.stringify(key)}].loaded = true
              const {${JSON.stringify(key)}: pkgDynamicImport} = importMap
              const res = await pkgDynamicImport()
              const exportModule = ${JSON.stringify(useDirectReactImport)} && ${JSON.stringify(key)} === "react"
                ? (res?.default ?? res)
                : {...res}
              // All npm packages pre-built by vite will be converted to esm
              Object.defineProperty(exportModule, "__esModule", {
                value: true,
                enumerable: false
              })
              return function () {
                return exportModule
              }
            },
            shareConfig: {
              singleton: ${shareItem.shareConfig.singleton},
              requiredVersion: ${JSON.stringify(shareItem.shareConfig.requiredVersion)},
              strictVersion: ${shareItem.shareConfig.strictVersion},
              ${shareItem.shareConfig.import === false ? 'import: false,' : ''}
            }
          }
        `;
        })
        .filter((x) => x !== null)
        .join(',')}
    }
      const usedRemotes = [${Object.keys(getUsedRemotesMap())
        .map((key) => {
          const remote = options.remotes[key];
          if (!remote) return null;
          return `
                {
                  entryGlobalName: ${JSON.stringify(remote.entryGlobalName)},
                  name: ${JSON.stringify(remote.name)},
                  type: ${JSON.stringify(remote.type)},
                  entry: ${JSON.stringify(remote.entry)},
                  shareScope: ${JSON.stringify(remote.shareScope ?? 'default')},
                }
          `;
        })
        .filter((x) => x !== null)
        .join(',')}
      ]
      export {
        usedShared,
        usedRemotes
      }
      `;
}

function getOrderedUsedShares() {
  const shares = new Set(getUsedShares());
  try {
    Object.keys(getNormalizeModuleFederationOptions().shared).forEach((pkg) => {
      if (!pkg.endsWith('/')) {
        shares.add(pkg);
        return;
      }
    });
  } catch {
    // Some isolated unit tests call generators before normalized options exist.
  }
  const sorted = Array.from(shares).sort((a, b) => {
    const priority = (pkg: string) =>
      pkg === 'react' ? 0 : pkg === 'react-dom' ? 1 : pkg.startsWith('react/') ? 2 : 3;
    return priority(a) - priority(b) || a.localeCompare(b);
  });
  return orderSharedDependenciesFirst(sorted);
}

function orderSharedDependenciesFirst(sharedPackages: string[]) {
  const sharedKeyByPackageName = new Map<string, string>();
  const subpathKeysByPackageName = new Map<string, string[]>();
  sharedPackages.forEach((pkg) => {
    const packageName = getPackageName(pkg);
    const existing = sharedKeyByPackageName.get(packageName);
    if (!existing || pkg === packageName) {
      sharedKeyByPackageName.set(packageName, pkg);
    }
    if (pkg !== packageName) {
      const subpaths = subpathKeysByPackageName.get(packageName);
      if (subpaths) subpaths.push(pkg);
      else subpathKeysByPackageName.set(packageName, [pkg]);
    }
  });
  const visiting = new Set<string>();
  const visited = new Set<string>();
  const ordered: string[] = [];
  const visit = (pkg: string) => {
    if (visited.has(pkg)) return;
    if (visiting.has(pkg)) return;
    visiting.add(pkg);
    const packageName = getPackageName(pkg);
    const packageJson =
      getInstalledPackageJson(pkg)?.packageJson ??
      (pkg !== packageName ? getInstalledPackageJson(packageName)?.packageJson : undefined);
    const dependencies = {
      ...((packageJson?.dependencies as Record<string, string> | undefined) || {}),
      ...((packageJson?.peerDependencies as Record<string, string> | undefined) || {}),
      ...((packageJson?.optionalDependencies as Record<string, string> | undefined) || {}),
    };
    Object.keys(dependencies).forEach((dependency) => {
      const sharedDependency = sharedKeyByPackageName.get(dependency);
      if (sharedDependency) visit(sharedDependency);
    });
    // A package's modules can consume its own shared subpath exports through
    // self-referencing bare specifiers at module-evaluation time, so subpath
    // share keys must come before their package root (see #767, #805).
    if (pkg === packageName) {
      (subpathKeysByPackageName.get(packageName) || []).forEach(visit);
    }
    visiting.delete(pkg);
    visited.add(pkg);
    ordered.push(pkg);
  };
  sharedPackages.forEach(visit);
  return ordered;
}

function getShareItemForPreload(pkg: string) {
  const shared = getNormalizeModuleFederationOptions().shared;
  const packageName = pkg.startsWith('@')
    ? pkg.split('/').slice(0, 2).join('/')
    : pkg.split('/')[0];
  const wildcardKey = `${packageName}/`;

  if (isExplicitSharedKey(pkg)) return shared[pkg];
  if (isExplicitSharedKey(wildcardKey)) return shared[wildcardKey];
  return undefined;
}

function generateSharedCacheSeedItem(pkg: string, shareItem: ShareItem, importPath: string) {
  const cacheDescriptor = getSharedCacheDescriptor(pkg, shareItem);
  return `if (__mfReadSharedCache(__mfModuleCache.share, ${JSON.stringify(cacheDescriptor)}) === undefined) {
        const mod = await import(${JSON.stringify(importPath)});
        ${normalizeRuntimeShareCode}
        const normalizedModule = __mfNormalizeRuntimeShare(mod);
        const exportModule = normalizedModule === mod ? {...mod} : normalizedModule;
        Object.defineProperty(exportModule, "__esModule", {
          value: true,
          enumerable: false
        });
        __mfWriteSharedCache(__mfModuleCache.share, ${JSON.stringify(cacheDescriptor)}, exportModule);
      }`;
}

const normalizeRuntimeShareCode = `const __mfNormalizeRuntimeShare = (mod) => {
            let current = mod;
            for (let i = 0; i < 5; i++) {
              const defaultExport = current?.default;
              if (!defaultExport || typeof defaultExport !== "object" || Object.keys(defaultExport).length === 0) break;
              const namedValues = Object.keys(current).filter((key) => key !== "default").map((key) => current[key]);
              if (namedValues.length > 0 && namedValues.some((value) => value !== undefined)) break;
              current = defaultExport;
            }
            return current;
          };`;

// Emitted into remoteEntry for import:false shared provider selection.
export const sharedProviderSelectionHelperCode = `const __mfOriginalProviderKey = Symbol("mf.originalSharedProvider");
          const __mfResolveShareHook = { emit: (params) => params };
          const __mfCreateProviderSelectionVersions = (versions, strategy) => {
            if (strategy !== "version-first") return versions;
            const selectionVersions = {};
            for (const [version, provider] of Object.entries(versions)) {
              selectionVersions[version] = Object.assign({}, provider, {
                loaded: false,
                loading: undefined,
                lib: undefined,
                [__mfOriginalProviderKey]: provider
              });
            }
            return selectionVersions;
          };
          const __mfSelectSharedProvider = (versions, pkg, share, strategy) => {
            if (!versions || !share) return undefined;
            const scopes = Array.isArray(share.scope) ? share.scope : [share.scope || "default"];
            const selectionVersions = __mfCreateProviderSelectionVersions(versions, strategy);
            const shareScopeMap = {};
            for (const scope of scopes) {
              shareScopeMap[scope || "default"] = { [pkg]: selectionVersions };
            }
            const selected = runtimeShare.getRegisteredShare(
              shareScopeMap,
              pkg,
              { ...share, scope: scopes, strategy },
              __mfResolveShareHook
            )?.shared;
            return selected?.[__mfOriginalProviderKey] || selected;
          };`;

function hasImportFalseShared(options: NormalizedModuleFederationOptions): boolean {
  return Object.values(options.shared ?? {}).some((share) => share?.shareConfig?.import === false);
}

function generateRuntimeSharedCacheSeedCode() {
  // Seeding a share evaluates its module graph, and every share proxy hit
  // during that evaluation must already be cached — the proxies defer their
  // local fallback until after init, so an unseeded proxy leaves its named
  // exports undefined at module-evaluation time. Seed dependencies and a
  // package's own subpath shares before the package itself.
  const seedOrder = getOrderedUsedShares();
  return `
    const __mfSeedOrder = ${JSON.stringify(seedOrder)};
    const __mfSeedKeys = __mfSeedOrder.filter((pkg) => usedShared[pkg] !== undefined);
    const __mfSeedPackageName = (pkg) => pkg.startsWith('@')
      ? pkg.split('/').slice(0, 2).join('/')
      : pkg.split('/')[0];
    for (const pkg of Object.keys(usedShared)) {
      if (__mfSeedKeys.includes(pkg)) continue;
      const packageName = __mfSeedPackageName(pkg);
      const rootIndex = __mfSeedKeys.indexOf(packageName);
      if (rootIndex === -1) {
        __mfSeedKeys.push(pkg);
        continue;
      }
      let insertIndex = rootIndex;
      while (
        insertIndex > 0 &&
        __mfSeedPackageName(__mfSeedKeys[insertIndex - 1]) === packageName &&
        __mfSeedKeys[insertIndex - 1] !== packageName
      ) {
        insertIndex--;
      }
      __mfSeedKeys.splice(insertIndex, 0, pkg);
    }
    for (const pkg of __mfSeedKeys) {
      const share = usedShared[pkg];
      const cacheDescriptor = __mfGetSharedCacheDescriptor(pkg, share.shareConfig?.singleton, share.version, share.scope);
      if (share.shareConfig?.import === false || __mfReadSharedCache(__mfModuleCache.share, cacheDescriptor) !== undefined) {
        continue;
      }
      const singletonCacheDescriptor = __mfGetSharedCacheDescriptor(pkg, true, share.version, share.scope);
      const singletonModule = __mfReadSharedCache(__mfModuleCache.share, singletonCacheDescriptor);
      if (singletonModule !== undefined) {
        __mfWriteSharedCache(__mfModuleCache.share, cacheDescriptor, singletonModule);
        continue;
      }
      const factory = await share.get();
      const mod = typeof factory === "function" ? factory() : factory;
      const resolved = await Promise.resolve(mod);
      ${normalizeRuntimeShareCode}
      const normalizedModule = __mfNormalizeRuntimeShare(resolved);
      const exportModule = normalizedModule === resolved ? {...resolved} : normalizedModule;
      Object.defineProperty(exportModule, "__esModule", {
        value: true,
        enumerable: false
      });
      __mfWriteSharedCache(__mfModuleCache.share, cacheDescriptor, exportModule);
    }`;
}

function getBrowserImportPath(importPath: string) {
  if (/^(?:[a-zA-Z]:[\\/]|\/)/.test(importPath) && !importPath.startsWith('/@')) {
    return `/@fs/${importPath}`;
  }
  return importPath;
}

function getHostAutoInitSharedSeedItems() {
  return getOrderedUsedShares()
    .map((pkg) => ({ pkg, shareItem: getShareItemForPreload(pkg) }))
    .filter(({ shareItem }) => shareItem?.shareConfig.import === false)
    .sort((a, b) => {
      const priority = (pkg: string) => (pkg === 'vue' ? 0 : pkg === 'pinia' ? 1 : 2);
      const aIsLocal = !!getLocalProviderImportPath(a.pkg);
      const bIsLocal = !!getLocalProviderImportPath(b.pkg);
      return (
        priority(a.pkg) - priority(b.pkg) ||
        Number(aIsLocal) - Number(bIsLocal) ||
        a.pkg.localeCompare(b.pkg)
      );
    });
}

function generateHostAutoInitSharedCacheSeedCode(command = 'build') {
  // In build mode, skip seeding for import:false modules. The bundler would
  // attempt to resolve their transitive dependencies which may not be
  // accessible (e.g. under pnpm strict mode). The runtime.loadShare() loop
  // that follows will handle acquiring these modules at runtime instead.
  if (command === 'build') return '';

  return getHostAutoInitSharedSeedItems()
    .map(({ pkg, shareItem }) => {
      if (!shareItem) return null;
      const importPath = getBrowserImportPath(getDirectSharedCacheSeedImportPath(pkg, shareItem));
      return generateSharedCacheSeedItem(pkg, shareItem, importPath);
    })
    .filter((item) => item !== null)
    .join('\n');
}

const REMOTE_ENTRY_ID = 'virtual:mf-REMOTE_ENTRY_ID';

export function getRemoteEntryId(
  options: Pick<NormalizedModuleFederationOptions, 'internalName' | 'filename'>
) {
  const scopedKey = `${options.internalName}__${options.filename}`.replace(/[^a-zA-Z0-9_-]/g, '_');
  return `${REMOTE_ENTRY_ID}:${scopedKey}`;
}
// SSR-only plugins import Node.js modules and must not be statically imported
// in the browser remote entry — doing so causes fileURLToPath / bare-specifier
// errors in the browser bundle. They are dynamically imported on the server only.
const SSR_ONLY_PLUGIN_SPECIFIERS = new Set(['@module-federation/vite/ssrEntryLoader']);
const isSsrOnlyPlugin = (importStatement: string) =>
  [...SSR_ONLY_PLUGIN_SPECIFIERS].some((s) => importStatement.includes(s));
const getSsrOnlyPluginSpecifier = (importStatement: string): string | undefined =>
  [...SSR_ONLY_PLUGIN_SPECIFIERS].find((s) => importStatement.includes(s));

export function generateRemoteEntry(
  options: NormalizedModuleFederationOptions,
  virtualExposesId = getVirtualExposesId(options),
  command = 'build'
): string {
  const needsSharedProviderSelectionHelper = hasImportFalseShared(options);
  const pluginImportNames = options.runtimePlugins.map((p, i) => {
    if (typeof p === 'string') {
      return [`$runtimePlugin_${i}`, `import $runtimePlugin_${i} from "${p}";`, `undefined`];
    } else {
      return [
        `$runtimePlugin_${i}`,
        `import $runtimePlugin_${i} from "${p[0]}";`,
        serializeRuntimeOptions(p[1]),
      ];
    }
  });

  return `
  // Shim Vue HMR runtime for dev-compiled components loaded by a non-Vite host.
  // When a remote is served by a Vite dev server, Vue's SFC compiler injects HMR
  // hooks that reference __VUE_HMR_RUNTIME__. This global only exists on pages
  // served by Vite's client runtime. When a production host loads the remote,
  // the HMR calls would throw. This no-op shim prevents that.
  if (typeof __VUE_HMR_RUNTIME__ === 'undefined') {
    globalThis.__VUE_HMR_RUNTIME__ = { createRecord() {}, rerender() {}, reload() {} };
  }
  import {init as runtimeInit, loadRemote} from "@module-federation/runtime";
  ${
    needsSharedProviderSelectionHelper
      ? 'import {share as runtimeShare} from "@module-federation/runtime/helpers";'
      : ''
  }
  ${pluginImportNames
    .filter((item) => !isSsrOnlyPlugin(item[1]))
    .map((item) => item[1])
    .join('\n')}
  ${
    command === 'build'
      ? getRuntimeInitResolveBootstrapCode()
      : getRuntimeInitBootstrapCode() + '\n  const { initResolve } = globalThis[globalKey];'
  }
  ${getRuntimeModuleCacheBootstrapCode()}
  const initTokens = {}
  const shareScopeName = ${JSON.stringify(options.shareScope)}
  const mfName = ${JSON.stringify(options.name)}
  let localSharedImportMapPromise
  let exposesMapPromise
  const shouldRetrySharedInitError = ${command !== 'build'} && ((error) => {
    const message = String((error && error.message) || error || '');
    return message.includes('Importing a module script failed') ||
      message.includes('Failed to fetch') ||
      message.includes('Load failed') ||
      message.includes('Outdated Optimize Dep');
  });
  const waitSharedInitRetry = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
  async function retrySharedInit(fn) {
    for (let attempt = 0; ; attempt++) {
      try {
        return await fn();
      } catch (e) {
        const canRetry = typeof shouldRetrySharedInitError === 'function' && shouldRetrySharedInitError(e);
        if (!canRetry || attempt >= 19) throw e;
        await waitSharedInitRetry(250);
      }
    }
  }
  ${needsSharedProviderSelectionHelper ? sharedProviderSelectionHelperCode : ''}

  async function getLocalSharedImportMap() {
    if (!localSharedImportMapPromise) {
      localSharedImportMapPromise = retrySharedInit(() => import("${getLocalSharedImportMapPath()}"))
        .catch((e) => { localSharedImportMapPromise = undefined; throw e; });
    }
    return localSharedImportMapPromise
  }

  async function getExposesMap() {
    if (!exposesMapPromise) {
      exposesMapPromise = retrySharedInit(() => import("${virtualExposesId}"))
        .then((mod) => mod.default ?? mod)
        .catch((e) => { exposesMapPromise = undefined; throw e; });
    }
    return exposesMapPromise
  }

  async function init(shared = {}, initScope = []) {
    ${sharedCacheHelperCode}
    const {usedShared, usedRemotes} = await getLocalSharedImportMap()
    try {
      const allInstances = globalThis.__FEDERATION__?.__SHARE__;
      if (allInstances) {
        ${normalizeRuntimeShareCode}
        for (const [, scopes] of Object.entries(allInstances)) {
          const scopeShare = scopes?.['${options.shareScope}'];
          if (!scopeShare) continue;
          for (const [pkg, versionMap] of Object.entries(scopeShare)) {
            const usedShare = usedShared?.[pkg];
            const selectedProvider = usedShare?.shareConfig?.import === false
              ? __mfSelectSharedProvider(versionMap, pkg, usedShare, '${options.shareStrategy}')
              : undefined;
            const providerEntries = usedShare?.shareConfig?.import === false
              ? Object.entries(versionMap).filter(([, provider]) => provider === selectedProvider)
              : Object.entries(versionMap);
            for (const [version, provider] of providerEntries) {
              if (!provider.lib) continue;
              const cacheDescriptor = __mfGetSharedCacheDescriptor(pkg, provider.shareConfig?.singleton, version, ${JSON.stringify(options.shareScope)});
              if (__mfReadSharedCache(__mfModuleCache.share, cacheDescriptor) !== undefined) continue;
              const mod = typeof provider.lib === "function" ? provider.lib() : provider.lib;
              const resolved = await Promise.resolve(mod);
              const normalized = __mfNormalizeRuntimeShare(resolved);
              __mfWriteSharedCache(__mfModuleCache.share, cacheDescriptor, normalized);
              if (provider.shareConfig?.singleton && usedShare) {
                const usedCacheDescriptor = __mfGetSharedCacheDescriptor(pkg, usedShare.shareConfig?.singleton, usedShare.version, usedShare.scope);
                if (__mfReadSharedCache(__mfModuleCache.share, usedCacheDescriptor) === undefined) {
                  __mfWriteSharedCache(__mfModuleCache.share, usedCacheDescriptor, normalized);
                }
              }
            }
          }
        }
      }
    } catch (e) {
      console.error('[Module Federation] Failed to bridge external shared modules', e)
    }
    for (const [pkg, share] of Object.entries(usedShared)) {
      const cacheDescriptor = __mfGetSharedCacheDescriptor(pkg, share.shareConfig?.singleton, share.version, share.scope);
      if (__mfReadSharedCache(__mfModuleCache.share, cacheDescriptor) !== undefined) continue;
      const singletonCacheDescriptor = __mfGetSharedCacheDescriptor(pkg, true, share.version, share.scope);
      const singletonModule = __mfReadSharedCache(__mfModuleCache.share, singletonCacheDescriptor);
      if (singletonModule !== undefined) {
        __mfWriteSharedCache(__mfModuleCache.share, cacheDescriptor, singletonModule);
      }
    }
    ${generateRuntimeSharedCacheSeedCode()}
    const __browserPlugins = [${pluginImportNames
      .filter((item) => !isSsrOnlyPlugin(item[1]))
      .map((item) => `${item[0]}(${item[2]})`)
      .join(', ')}];
    const __ssrPlugins = typeof globalThis.window === 'undefined'
      ? await Promise.all([${pluginImportNames
        .filter((item) => isSsrOnlyPlugin(item[1]))
        .map((item) => {
          const specifier = getSsrOnlyPluginSpecifier(item[1])!;
          const opts = item[2];
          return `import(${JSON.stringify(specifier)}).then(m => (m.default ?? m)(${opts}))`;
        })
        .join(', ')}])
      : [];
    const initRes = runtimeInit({
      name: mfName,
      remotes: ${options.shareStrategy === 'loaded-first' ? '[]' : 'usedRemotes'},
      shared: usedShared,
      plugins: [...__browserPlugins, ...__ssrPlugins],
      ${options.shareStrategy ? `shareStrategy: '${options.shareStrategy}'` : ''}
    });
    // handling circular init calls
    var initToken = initTokens[shareScopeName];
    if (!initToken)
      initToken = initTokens[shareScopeName] = { from: mfName };
    if (initScope.indexOf(initToken) >= 0) return;
    initScope.push(initToken);
    initRes.initShareScopeMap('${options.shareScope}', shared);
    try {
      await retrySharedInit(async () => {
        await Promise.all(await initRes.initializeSharing('${options.shareScope}', {
          strategy: '${options.shareStrategy}',
          from: "build",
          initScope
        }));
      });
    } catch (e) {
      console.error('[Module Federation]', e)
    }
    for (const [pkg, share] of Object.entries(usedShared)) {
      const cacheDescriptor = __mfGetSharedCacheDescriptor(pkg, share.shareConfig?.singleton, share.version, share.scope);
      if (share.shareConfig?.import !== false || __mfReadSharedCache(__mfModuleCache.share, cacheDescriptor) !== undefined) continue;
      ${normalizeRuntimeShareCode}
      const versions = shared?.[pkg];
      const provider = __mfSelectSharedProvider(versions, pkg, share, '${options.shareStrategy}');
      if (!provider) continue;
      const factory = provider.lib || (provider.loading ? await provider.loading : await provider.get?.());
      const mod = typeof factory === "function" ? factory() : factory;
      const resolved = await Promise.resolve(mod);
      __mfWriteSharedCache(__mfModuleCache.share, cacheDescriptor, __mfNormalizeRuntimeShare(resolved));
    }
    initResolve(initRes)
    return initRes
  }

  async function getExposes(moduleName) {
    const exposesMap = await getExposesMap()
    if (!(moduleName in exposesMap)) throw new Error(\`[Module Federation] Module \${moduleName} does not exist in container.\`)
    if (__mfModuleCache.pendingShareLoads) {
      await Promise.all(__mfModuleCache.pendingShareLoads)
    }
    return (exposesMap[moduleName])().then(res => () => res)
  }
  export {
      init,
      getExposes as get
  }
  `;
}

/**
 * Inject entry file, automatically init when used as host,
 * and will not inject remoteEntry
 */
export const HOST_AUTO_INIT_TAG = '__H_A_I__';
const hostAutoInitModule = new VirtualModule('hostAutoInit', HOST_AUTO_INIT_TAG);
let currentHostAutoInitRemoteEntryId = REMOTE_ENTRY_ID;
let currentHostAutoInitCommand = 'build';
export function generateHostAutoInitCode(remoteEntryImport: string, _command = 'build') {
  const shouldPreloadShares =
    getNormalizeModuleFederationOptions().shareStrategy !== 'loaded-first';
  return `
    ${getRuntimeModuleCacheBootstrapCode()}
    let hostInitPromise;
    async function initHost() {
      if (!hostInitPromise) {
        hostInitPromise = (async () => {
          ${sharedCacheHelperCode}
          ${generateHostAutoInitSharedCacheSeedCode(_command)}
          const remoteEntry = await import(${remoteEntryImport});
          const runtime = await remoteEntry.init();
          const {usedShared} = await import("${getLocalSharedImportMapPath()}");
          ${normalizeRuntimeShareCode}
          ${
            shouldPreloadShares
              ? `
          for (const [pkg, share] of Object.entries(usedShared)) {
            const cacheDescriptor = __mfGetSharedCacheDescriptor(pkg, share.shareConfig?.singleton, share.version, share.scope);
            if (__mfReadSharedCache(__mfModuleCache.share, cacheDescriptor) !== undefined) {
              continue;
            }
            await runtime.loadShare(pkg, {
              customShareInfo: { shareConfig: share.shareConfig }
            }).then((factory) => {
              const mod = typeof factory === "function" ? factory() : factory;
              return Promise.resolve(mod).then((resolved) => {
                __mfWriteSharedCache(__mfModuleCache.share, cacheDescriptor, __mfNormalizeRuntimeShare(resolved));
              });
            });
          }
          `
              : ''
          }
          const __mfRemotePreloads = [];
          await Promise.all(__mfRemotePreloads);
          return runtime;
        })();
      }
      return hostInitPromise;
    }
    hostInitPromise = initHost();
    export { initHost, hostInitPromise };
    `;
}
export function writeHostAutoInit(remoteEntryId = REMOTE_ENTRY_ID, command = 'build') {
  currentHostAutoInitRemoteEntryId = remoteEntryId;
  currentHostAutoInitCommand = command;
  hostAutoInitModule.writeSync(
    generateHostAutoInitCode(JSON.stringify(remoteEntryId), command),
    true
  );
}
export function refreshHostAutoInit() {
  try {
    writeHostAutoInit(currentHostAutoInitRemoteEntryId, currentHostAutoInitCommand);
  } catch {
    // Some isolated unit tests exercise share/remote plugins without
    // initializing normalized federation options.
  }
}
export function getHostAutoInitImportId() {
  return hostAutoInitModule.getImportId();
}
export function getHostAutoInitPath() {
  return hostAutoInitModule.getImportId();
}
