#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Format staged files
npx pretty-quick --staged

# Build project
pnpm build

# Check if the server is already running on http://localhost:5173
if ! pnpm exec wait-on http://localhost:5173 --timeout 5000; then
  # If not running, start multi-example in the background
  pnpm run multi-example &
  # Wait for the server to be ready before proceeding
  pnpm exec wait-on http://localhost:5173
fi

# Run Playwright tests after ensuring the server is up
pnpm playwright test --project=vite-webpack-rspack
