name: Runtime E2E tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  pull-requests: read

jobs:
  run-e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack and Setup PNPM
        run: |
          corepack enable
          corepack prepare pnpm@9.1.3 --activate

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run E2E Tests
        working-directory: ./packages/module-federation-vite-runtime
        run: pnpm e2e --run --reporter=json --outputFile=./reports/e2e/output.json

      - name: Upload Artifacts on Failure
        working-directory: ./packages/module-federation-vite-runtime
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: reports/e2e/output
          retention-days: 3
