name: multi-example – e2e tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  run-playwright-tests:
    name: Playwright Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.58.2-noble
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: PNPM Install
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 10.28.2

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Libs
        run: pnpm build && pnpm build:shared-lib

      - name: Run Playwright Tests
        run: pnpm playwright test

      - name: Upload Artifacts on Failure
        if: failure()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: test-results
          path: reports/e2e/output
          retention-days: 3
