name: Integration Test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  pull-requests: read

jobs:
  integration-test:
    name: Integration (${{ matrix.bundler }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        bundler: ['vite@5', 'vite@6', 'vite@7.3.1', 'vite@8.0.0-beta.15', 'rolldown-vite@7.3.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: PNPM Install
        uses: pnpm/action-setup@v4
        with:
          version: 10.28.2

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/

      - run: corepack enable

      - name: Install NPM Dependencies
        run: pnpm install --frozen-lockfile

      - name: Override bundler version
        run: pnpm add -Dw ${{ matrix.bundler }}

      - name: Run Integration Tests
        run: pnpm test:integration
