name: Release @module-federation/vite

on:
  - workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: monorepo

      - name: PNPM Install
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23.5.0
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/

      - run: corepack enable

      - name: Install NPM Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: ./packages/module-federation-vite
        run: pnpm run build

      - name: Publish to npm
        working-directory: ./packages/module-federation-vite
        run: npm publish --access public --tag 2.0.0-alpha-1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
